### PR TITLE
chore: merge `next` branch into `master`

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

Current `next` branch contains a PR #17611 that should be included in v5.5.0.

### CODE REVIEW

**Comment by Ovilia** [comment]
The next version may not be 5.5.0. If there aren't enough major features, we may still release 5.4.3. So perhaps we should wait until we decide if we should release 5.5.0 as the next version?

**Comment by plainheart** [comment]
@Ovilia Looked through the merged pull requests, the most are to fix bugs. I have no objection to releasing v5.4.3 instead of v5.5.0.

**Comment by plainheart** [comment]
Let's create a milestone for v5.4.3 and move the pull requets and issues to it.

**Comment by Ovilia** [comment]
@plainheart Do you think it could be 5.5.0 if I can complete the SSR client runtime before the next release? I'm working on the building scripts and should be ready in a few days.

**Comment by plainheart** [comment]
@Ovilia I think the SSR client runtime module could be released together with other three great features like #17471, #17461 and #17611 in v5.5.0. But before that, we can also release a minor version v5.4.3 for bug fixes.

**Comment by Ovilia** [comment]
@plainheart Sure. Let's start the release of 5.4.3 soon. Should this PR be closed for now or turn it into draft?

**Comment by plainheart** [comment]
@Ovilia I've listed it in v5.5.0. Just leave it alone until v5.5.0 is ready to release.

**Review by Ovilia — APPROVED** [review]

**Comment by tyn1998** [comment]
Thank you all for reviewing and testing the PR and really excited to see the minor work being merged into `master`! I hope I can contribute more to this wonderful project in future ❤️

**Pull request merged**
