### PR TITLE
fix: import theme error

### PR DESCRIPTION
**Pull request by lz1998**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?
fix https://github.com/apache/echarts/issues/14351#issuecomment-785905520

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by pissang** [comment]
In 5.0, we changed require(`echarts`) to  require(`echarts/lib/echarts`) to avoid bundling the whole package accidentally when importing themes. I guess we need to find a better solution

**Comment by lz1998** [comment]
This is my code. Line `require("echarts/theme/vintage")` report this error

```javascript
import {createCanvas} from 'canvas'
import * as echarts from 'echarts'
import Express from 'express'
import {Request, Response} from 'express'

// 导入主题
require("echarts/theme/vintage")


// 生成图片
function generateImage(options: any, width: number, height: number, theme: string) {
  console.log("GENERATE IMAGE")
  console.log(`WIDTH: ${width}`)
  console.log(`HEIGHT: ${height}`)
  console.log(`THEME: ${theme}`)
  console.log(`OPTIONS: ${JSON.stringify(options)}`)
  const canvas = createCanvas(width, height) as any
  const ctx = canvas.getContext('2d')
  ctx.font = '12px'
  echarts.setCanvasCreator(() => canvas)
  const chart = echarts.init(canvas, theme)
  options.animation = false
  chart.setOption(options)
  return (chart.getDom() as any).toBuffer()
}

const express = require('express')
const app = Express()
app.use(express.json())
const imgController = (req: Request, res: Response) => {
  console.log("RECV REQ")
  let options = req.query.options || req.body
  if (typeof options === 'string') {
    options = JSON.parse(options)
  }
  let width = parseInt(req.query.width || options.width || 1024)
  let height = parseInt(req.query.height || options.height || 768)
  let theme = req.query.theme || options.theme || 'dark'
  res.header("Content-Type", "image/png")
  res.send(generateImage(options, width, height, theme))
}
app.post('/', imgController)
app.get('/', imgController)

const PORT = process.env.PORT || 3000
app.listen(PORT)
console.log("echarts started port:" + PORT)

```

Error
```bash
/Users/lz1998/WebstormProjects/ssr-echarts/node_modules/echarts/lib/echarts.js:44
export * from './export/core';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.require.extensions.<computed> [as .js] (/Users/lz1998/WebstormProjects/ssr-echarts/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/lz1998/WebstormProjects/ssr-echarts/node_modules/echarts/theme/vintage.js:29:26
    at Object.<anonymous> (/Users/lz1998/WebstormProjects/ssr-echarts/node_modules/echarts/theme/vintage.js:34:3)

```

**Comment by plainheart** [comment]
A transpilation from ES6 module to `commonjs` module may be required for `export * from xxx`.

**Comment by lz1998** [comment]
> A transpilation from ES6 module to `commonjs` module may be required for `export * from xxx`.

When will it be fixed?

**Pull request closed without merging**
