### PR TITLE
Accept GeometryCollection

### PR DESCRIPTION
**Pull request by mathiasleroy**
1) Changed the filter to avoid errors with missing coordinates of GeometryCollection.
2) Added a rule to push the coordinates of GeometryCollection like it was done for type='MultiPolygon' and 'Polygon'

### CODE REVIEW

**Comment by mathiasleroy** [comment]
This is a fix for issue #9350
https://github.com/apache/incubator-echarts/issues/9350

**Comment by mathiasleroy** [comment]
I use this pr in production, it's working. Please solve this issue.

**Comment by poenel** [comment]
why is this logic missing in v5.3.3, there still have problem with issue #9350.

**Comment by WangNingning1994** [comment]
Any updates?

**Pull request closed without merging**
