### PR TITLE
feat(pictorialBar): support clip for pictorialBar series

### PR DESCRIPTION
**Pull request by Ovilia**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

Support clip for pictorialBar series.

### Fixed issues

#19173

### Before: What was the problem?

Pictorial bars may overflow the grid area.

### After: How does it behave after the fixing?

User can set `series.clip: true` to enable clipping.

## Document Info

One of the following should be checked.

- [ ] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [x] The document changes have been made in apache/echarts-doc#365

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by linghaoSu** [comment]
image

It seems that when the label is placed outside the bar, it will be clipped. Is this expected?

[label cliped live demo](https://echarts.apache.org/examples/zh/editor.html?version=PR-19197%40f38c2a6&code=G4QwTgBGD2DGDWBTALhAvAKAhA5ABxGQAsAuAejIFkBaAJgBZ6A6AZgE4A2AGkdbbdgAGLsMFN6AdjpM2LAIzT6tKRyYBWObVi0mADjltquprVpyuLEwrlqmEwWwtXqNuw4DOtiWzVc5rXRYuLx8uCVZaNQBhOhZw_V0LNiYObzpedm4M_nTmTJ48_gAvCBpaDjE483oxXWUhEWpLXX0XHTZ6Dia9VrljeQFBRTluMXLaamY1DlGUjkNVDQkiOXCOXXohcTlzfx9aERSJX2Y5QXpD1N9FgwbbWjYFZok_ftXu3Re-1lWACToKqwJHISmU1MwJPRfN8fHJYC4ZI4hpYKkF_KkuijBEFLJDNsIdIJ1n4UponHinKjyYxYHsWiJKYIJuiJNwsRNcYwAMp0NQ6Y5fYyw3kQqGvGQaUG82x88w6Uy6YDUWwOXQrcRM4DMTgCdHYklmIK2DrmFXzMIyQS7HRqIgucKCaIA_xxILhV288IMXyWNRqXTS9RmLjy2i6IplDgql7ZQaNRYSKQQszUBNSOTMXScITKmRKYJ2DrUd2RAveejFiJqdyVWQW-j0yxmXZeQS6GLlGXsHj-TqGTtMQQxwr9qOD4d8NhSyI6FhZWw2AA2CNWXX8pgAMiK7FmeLpl73PpNB_MD4ODCGmDsOGeGwHmuUiMYiRItzPWPOr2oijgANwYaA8GQABLaAADt0AgABvLAIFgaBF2gMASAgABtHAAGIACMsMEPD6BwLhcAwgAxEiABEGwAQRwABdLhYMXRAAHNEDAgATFCYOwbB2MIEAUPQvBgNgZAkOAkBFwgRAmIAWzY5BCNwMBEAAM0QFSwNgRAICw8A6NggBfBjsAADyo0zgPcLjYN4_jBJwEAlJwLDnNgZz2LokyeJASz3AAFRE-AbJ4nj3CIaAAHcUNUyT3EQWyIGMxLfKsjcQCwmSQtCiBgLA5ANNARcUMERLDKM7yAE8LKs7LsFkvKULObzsHcPBF2A5ANzyxAuIgcKopiuKdPK7BkuwZiwGAzjoMSpjVOQFCahaqBgOYohFogM4Ktg-KpsQay0MS7icuQSq8F63BhNE8TJIAIX0lbsDAkB5JQ_ARLEqbJOkuSFMIxLWsq2SsIQlCYAQFAnrgjq8BQ5AwAAV0QaGiia4RAYgRcMqy2acrCiLoogBHkaIvBoHcTrQLA97oER5BKfYxAAfx3irOQEAtMuoxofGnK-I5wTMewE7WYgIrkZQipodC9xgdBxcuWAopLtQ4WcpwNRBAAUhZsWeJwM4dZwCAKC2vDtYgaBVOJogdLttaNqtm2VPUzTtN08AmHV7BaPVvn8dF1mJcu6Wff6-WEKVlWhf1g2td1mWcs0QRTbICASOA0zEHYiAHfW1AQ-9uO_bFgOcqD_GQ6ljG47lkGo-Vy6tbTiAAFEAEdEeAoqFOJ6A0K1oitdL1ny9CyucuriAw7ryPFwAJUQC7CHhpGUfD-uFejy6cHsXXW877ve_y_u0L342iIv3XR7Fs2qI43ToGICBIuml_Odz_OnYusBtPykArEIDgB0rASSsBEbYwKrnPS8V2LhzNuBW2Ok37sRftbKAakNJsQ9npSAkU7YQS3ghJeK9UCIzgcXMemNb5JRWpPM6F13p4L1qFF6b1lJYPdjpFh0M8EAHEQBw1wC4C2rCeICwEmhaWM9hCyKIhUWho0IB-0Mv-e-7Fc5M3cLAKaQFqbuG9qpRGWkQJIJAJo8iB1dHAX0eBdwAAKAAlHjcW4AIDaJsXYsC7hIJq1Cv4jWxDFZN0EgAIgTmEoiYSjbazCbRcR2AcD-SIIQXK1lEm4ATs7TBbscE8Pcag4gmTDYWxya7bBXNPaQG_sgJgOBEr0USoE0KOBgk73CZEoiKcEnQ2Sak1AtUSnZIwRU7h1TX7vyIFwEpqks45zzogR2qAU71MaStdC7TQkQC1s5RAXce6ST7mJQeciR5eWaZjNp88OkQDCfvMJJT9nHyOafE5qF7k6yiXch5vSrklIAOqEIjg3Rey9EBpIoTnIioNil9KKUQYBj9akQF_v_DmQCQElLAYuCBUCFmwIWUg4gKCpnOxKWM_J1S1mhVHrRf89VKpRFSWAOp8VkAAHlvEOOOpjSaQiiAiRQoBMxYEmDmT8kwSRTBZJCIccY0x1MIAOM6ogWSAA5V6KNcocUQKZFxk9sAqWQIjMAEFDU8UYbvSadM8CZNCuTSmoqUKySZSyup8EwLAA0sgfy0AAAK8zFwOJwJNaaSlUJ5SZqZIi9haJOKTtgWAgrFzsU0rHOOrjM3E3OrvAqplFKJpyvNTaOB0UaXtazMSwicANU0UxSt-N3BnSYnVbNxM9WbU8Xo0V7hI26tMrRJgAAraAeUQ0AB0wI4ATeHfGczFzFWIjhPC5wGntroXOniaNzZyC3cosWtDQpqMxoZJxZV6H9WAkxfKa9kZJVgk4_85V2WBXknTZA8qTGiSVc41xFj2JWJ0T2gxziGUQFdcy8AdTwIhsRngAWOclIAaA143tT6MDGXNoIJ9QA)

**Comment by Ovilia** [comment]
@linghaoSu Thanks for correcting. I think this is not ideal. I will try to fix this.

**Comment by Ovilia** [comment]
@linghaoSu It seems that if the clipPath is added on the `bar.__pictorialBundle`, there would be an extra transform on the clipPath and makes the whole shape invisible. Do you have any suggestion?

**Review by plainheart — COMMENTED** [review]
How about preventing the label from being clipped by setting the label `ignoreClip` to be `true`?

**Comment by Ovilia** [comment]
> How about preventing the label from being clipped by setting the label `ignoreClip` to be `true`?

Thanks for the hint! It's a good idea.

@linghaoSu @plainheart Please help review again. Thanks

**Review by linghaoSu — COMMENTED** [review]
Looks good to me.

**Review by plainheart — APPROVED** [review]

**Pull request merged**
