### PR TITLE
fix(dataZoom): add event for `SliderZoom`

### LINKED ISSUE #15775: dataZoom click not working
### Version
5.2.1

### Reproduction link
[https://jsfiddle.net/tmtron/9y0xtqs7/11/](https://jsfiddle.net/tmtron/9y0xtqs7/11/)

### Steps to reproduce
click on the dataZoom

### What is expected?
click event should be invoked

### What is actually happening?
click event is not invoked

---
The example from the [documentation: echartsInstance. on](https://echarts.apache.org/en/api.html#echartsInstance.on) is also not working:
```javascript
chart.on('click', 'dataZoom', function () {...});
```

* Other click events work: e.g. on the series, axis-labels (when `triggerEvent` is set to `true`)
* but for [dataZoom](https://echarts.apache.org/en/option.html#dataZoom), `triggerEvent` does not exist
* Maybe someone knows a temporary workaround?
  * I thought about using [echartsInstance.containPixel](https://echarts.apache.org/en/api.html#echartsInstance.containPixel), but it seems, that this does also not support `dataZoom`

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Add mouse event for `SliderZoom`

### Fixed issues

- Close #15775 

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by pissang** [comment]
I'm not sure if this event is what the issue want. Seems we can do very few things with parameters `componentType` and `componentIndex` only.

**Comment by susiwen8** [comment]
What else should we provide for user?  @pissang

**Comment by pissang** [comment]
@susiwen8 I'm not sure, perhaps we can follow up that issue to figure out the use case?

**Comment by susiwen8** [comment]
@pissang As user request. I have added `value` info in `eventData`. Please review it.

**Pull request closed without merging**
