### PR TITLE
fix(lines): Lines series symbolSize cannot be updated. close #18350

### LINKED ISSUE #18350: [Bug] Lines series symbolSize cannot be updated
### Version

5.4.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=lines-ny&code=MYewdgzgLgBAtgQwB4DUEBsCuBTGBeGARgAZiBuAWAChr0BLMbCAEQSgXxgEEAnHhAJ4A6AGY8QcABS9-AyYlQYcASiEBrbAIiTlqxAAdJkgG5Lsy_AD4YAb2owYPbFEw8wt-w5igQPACYQAFwwANqeXqGmWLgAVDAAsmwAFkL8YH4SOgA0MFE4MHGJUClpGVLKALpZ4V4hebEJyakI6ZnKOfUFjcXNreUVNQNUDgC-lFQjyuPUIPpQdOCcdsMwSFxIdEEeKw5QAvrYwQDk9UfVO_AMwcTnEQrBCmjRtzAjLwLrm8HLEXsHx6cXg44FcYDcavd4MgnjgXm8an42AgAFogCTfGp_Q4wI4MCB0PzYM41NYbCAASXS2CQ1yBMA-ZMphJpYLp0AQPCgMOx4Iu2HS3Ie0LMcJeEGwPDoTGCYQuPwiMAJx0IxIuu322KO9EYEFVCpgEAEcAARiB0DKjmBwESckcOeIAO5HKo1ByGk1mgDKdAAXtiAKx0hw-fwMNjYT1aKDYODHYAc6P4loAJj8eoV2oje3Q2Pl-tA6F8xwAxMAACwANmw_rL6f1DoJxWChFdryDMER7GCmZYSLp8JWLom0yoAHpRzAAMJJFoAcyYMGKuEzMAbfmKOQLvhgLT8BqNpvQ3r9q6S_I7IEwxpzAFpgPRgGpqHABNOE0JwJIjn5r_e6I-zhgERMDAYB5k_fQOQQOAIAseUXzfTkhHFKAAHk5gWMBJHlcVJWlUIajzLwlRxFV2yxY4ezrLx3UPC0rUYQC7T4EAnSHfVaK9X1sRIdsQz8MNo0jaAYzjBMmDoFM03bTNPWzXNW2DM0ixxa8EAA9sHDXJsYAAZlbAd9U7BBuwYJhWHYfsXiGN5bEcbB9HQdTsHiCV5wtXCpV1CpXmUagRmoZQgA

### Steps to Reproduce

1. Double clicking on the charts to update the styles of lines

### Current Behavior

The width and color of lines are changed based on the new option, but symbolSize isn't changed

### Expected Behavior

The styles of lines must be corresponding with the new option

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by cvSoldier**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Solve the bug that attributes such as symbolSize will not be updated by using all attributes of symbol as value

### Fixed issues

- #18350 

### Before: What was the problem?

The width and color of lines are changed based on the new option, but symbolSize isn't changed

### After: How does it behave after the fixing?

The styles of lines must be corresponding with the new option

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

## Others
[Link to Minimal Reproduction](https://echarts.apache.org/examples/en/editor.html?c=lines-ny&code=MYewdgzgLgBAtgQwB4DUEBsCuBTGBeGARgAZiBuAWAChr0BLMbCAEQSgXxgEEAnHhAJ4A6AGY8QcABS9-AyYlQYcASiEBrbAIiTlqxAAdJkgG5Lsy_AD4YAb2owYPbFEw8wt-w5igQPACYQAFwwANqeXqGmWLgAVDAAsmwAFkL8YH4SOgA0MFE4MHGJUClpGVLKALpZ4V4hebEJyakI6ZnKOfUFjcXNreUVNQNUDgC-lFQjyuPUIPpQdOCcdsMwSFxIdEEeKw5QAvrYwQDk9UfVO_AMwcTnEQrBCmjRtzAjLwLrm8HLEXsHx6cXg44FcYDcavd4MgnjgXm8an42AgAFogCTfGp_Q4wI4MCB0PzYM41NYbCAASXS2CQ1yBMA-ZMphJpYLp0AQPCgMOx4Iu2HS3Ie0LMcJeEGwPDoTGCYQuPwiMAJx0IxIuu322KO9EYEFVCpgEAEcAARiB0DKjmBwESckcOeIAO5HKo1ByGk1mgDKdAAXtiAKx0hw-fwMNjYT1aKDYODHYAc6P4loAJj8eoV2oje3Q2Pl-tA6F8xwAxMAACwANmw_rL6f1DoJxWChFdryDMER7GCmZYSLp8JWLom0yoAHpRzAAMJJFoAcyYMGKuEzMAbfmKOQLvhgLT8BqNpvQ3r9q6S_I7IEwxpzAFpgPRgGpqHABNOE0JwJIjn5r_e6I-zhgERMDAYB5k_fQOQQOAIAseUXzfTkhHFKAAHk5gWMBJHlcVJWlUIajzLwlRxFV2yxY4ezrLx3UPC0rUYQC7T4EAnSHfVaK9X1sRIdsQz8MNo0jaAYzjBMmDoFM03bTNPWzXNW2DM0ixxa8EAA9sHDXJsYAAZlbAd9U7BBuwYJhWHYfsXiGN5bEcbB9HQdTsHiCV5wtXCpV1CpXmUagRmoZQgA)

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — CHANGES_REQUESTED** [review]
Looks good to me. Thanks for your contribution. Please [add a test case](https://github.com/apache/echarts/wiki/How-to-make-a-pull-request#test).

**Comment by Ovilia** [comment]
Hi, at the top menu, please check the first checkbox and select the latest nightly build of 5.4.x so that your local code is compared to current master code. If the checkbox is not selected, it's compared to the last release, so that there are many code not related to your pull request.

**Comment by Ovilia** [comment]
Please fix the lint problem in the CI.

**Comment by cvSoldier** [comment]
found that ci failed again,:worried: but I didn't understand the reason. Do I need to commit any changes?

**Comment by cvSoldier** [comment]
Hi @Ovilia. Since all checks have passed, may I ask if it's ready for merging now？
(kind of exciting for becoming a contributor)

**Review by Ovilia — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
