### PR TITLE
fix(marker): add missing type for symbolOffset, fix symbolOffset & symbolKeepAspect doesn't work in markPoint.

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Enhance #14375

- add missing value type `string | number` to `symbolOffset`
- add missing return type `string | number` to `SymbolOffsetCallback`
- fix `symbolOffset` & `symbolKeepAspect` doesn't work in `markPoint`
- fix `symbolOffset` type issue in `SilderTimelineView`
- extract `normalizeSymbolSize` & `normalizeSymbolOffset` to the common symbol util.

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by plainheart** [comment]
Currently, the logic about parsing `symbolOffset` with `numberUtil.parsePercent` and `symbolSize` is used in many places. I'm thinking to extract it into a common helper to reduce redundant code and bundled size.

**Comment by PiterYang** [comment]
when can publish a new version for this merge ?

**Review by Ovilia — COMMENTED** [review]
LGTM

**Comment by Ovilia** [comment]
> when can publish a new version for this merge ?

@PiterYang This PR is set to be in 5.2.0, which should be released in about a month.

**Comment by packjie** [comment]
I encountered the same problem. After upgrading the version, markpoint fell down. After checking, I found that the value of symboloffset did not work.
image
 After reading this post, I changed the original file
1、node_ modules/echarts/lib/component/marker/MarkPointView.js
image
image
The problem was solved and the chart returned to normal
image

**Review by pissang — APPROVED** [review]

**Comment by osgregs** [comment]
ty, waiting new version.

**Comment by Flourad** [comment]
求问下这个特性什么时候能发布呀？

**Comment by alanhu151** [comment]
> > when can publish a new version for this merge ?
> 
> @PiterYang This PR is set to be in 5.2.0, which should be released in about a month.

When the 5.2.0 will be released? checked everyday for months. :(

**Pull request merged**
