### PR TITLE
fix: markArea of bar series now covers whole categories specified

### LINKED ISSUE #3573: bar 类型图表 markArea 能否标记一个区间
#### 问题简述 (One-line summary)

能否只在2月的区间添加markArea 也就是从2月的左侧标线到二月的右侧标线之间的区域
现在只能像下边的图片横跨多个月份
另外官网关于markArea的API和提供的例子不对应，望改正。
image
#### 版本及环境 (Version & Environment)
- ECharts 版本 (ECharts version): 官网在线测试
- 浏览器类型和版本 (Browser version): chrome
- 操作系统类型和版本 (OS Version): mac OS X 10.10.5
#### 重现步骤 (Steps to reproduce)

1.
2.
#### 期望结果 (Expected behaviour)

bar 类型图表 只在一个区间有markArea背景
#### ECharts配置项 (ECharts option)

``` javascript

option = {
    title : {
        text: '某地区蒸发量和降水量',
        subtext: '纯属虚构'
    },
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['蒸发量','降水量']
    },
    toolbox: {
        show : true,
        feature : {
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            data : ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'蒸发量',
            type:'bar',
            data:[2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3],
            markPoint : {
                data : [
                    {type : 'max', name: '最大值'},
                    {type : 'min', name: '最小值'}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name: '平均值'}
                ]
            },
            markArea: {
                data: [ [{
                    // name: '早高峰',
                    xAxis: '1月'
                }, {
                    xAxis: '3月'
                }] ]
            }
        },
        {
            name:'降水量',
            type:'bar',
            data:[2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3],
            markPoint : {
                data : [
                    {name : '年最高', value : 182.2, xAxis: 7, yAxis: 183},
                    {name : '年最低', value : 2.3, xAxis: 11, yAxis: 3}
                ]
            },
            markLine : {
                data : [
                    {type : 'average', name : '平均值'}
                ]
            },

        }
    ]
};
```

### LINKED ISSUE #12341: markArea xAxis does not work as expected for category axis and bar series
### Version
4.7.0

### Reproduction link
[https://jsfiddle.net/758vs6xe/](https://jsfiddle.net/758vs6xe/)

### Steps to reproduce
You have an xAxis of type category and you have a bar series. And you want to markArea of a specific category. You can't because the markArea starts drawing from the center of the bar.

In the example we have the days of the week as categories.
With markArea 'Mon' - 'Tue' you see something.
With markArea 'Wed' - 'Wed' you see nothing.

Screenshot from 2020-03-27 17-36-55

### What is expected?
For markArea to mark the specific bar category.

### What is actually happening?
It doesn't mark it.

### LINKED ISSUE #17021: [Feature] Get calculated max/min value of yaxis
### What problem does this feature solve?

I would like to retrieve the automatically calculated min/max value of an yaxis. 

### What does the proposed API look like?

I'm unsure about this. There seems to be no getter API except for chart.getOption(). Using this seems like a hack as the option property would only be readable but not writable using setOption().
`option.yAxis[1].minCalculated`

### PR DESCRIPTION
**Pull request by jiawulin001**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

MarkArea in `bar series/category axis` now covers the categories specified rather than area between bars of specified categories.

### Fixed issues

- fix #3573
- fix #17021
- fix #12341

### Before: What was the problem?

MarkArea in `barSeries/category-axis` is marking the area between bars of category specified, which is not wanted in category axis chart.

|#3573|image|
|--|--|
|#12341|image|
|--|--|
|#17021|image|

### After: How is it fixed in this PR?

Now markArea marks the whole category zones specified. Multi-bars and invert input are both considered.
### Left MarkArea
```
markArea: {
          data: [
            [
              {
                name: `Invert input`,
                xAxis: 'Thu'
              },
              {
                xAxis: 'Mon'
              }
            ]
          ]
        }
```
### Left MarkArea
```
markArea: {
          data: [
            [
              {
                name: 'Single Emphasis',
                xAxis: 'Sun'
              },
              {
                xAxis: 'Sun'
              }
            ]
          ]
        }
```
after #17021

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

bar-markArea.html

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by dynamikus** [comment]
Any plans to merge this pr?

**Comment by Ovilia** [comment]
@dynamikus Thanks for your contribution and please be patient to wait for reviews since we are mostly working part-time on the project. :)

**Comment by Ovilia** [comment]
This PR looks awesome! I would like to see more test cases, for example, when `xAxis` and `yAxis` are both configured in the data, or `x` and `y` values.

**Comment by dynamikus** [comment]
@jiawulin001 
Thank you for looking into this. Sorry if my questions sounded condescending or demanding that was never my attention.
Keep up with the great work 👍

**Comment by jiawulin001** [comment]
> I would like to see more test cases

@Ovilia More test cases are on the way.

>Sorry if my questions sounded condescending or demanding that was never my attention.
Thank you for your applause, and it's totally fine to ask. I am really glad if my work can help someone else.

**Comment by jiawulin001** [comment]
@Ovilia A new test case in the same html is added

**Comment by Ovilia** [comment]
@jiawulin001 Thanks! Please also run the [visual test](https://github.com/apache/echarts/wiki/How-to-make-a-pull-request#run-test-cases) for all cases and see if there are diffs that we should be aware of.

**Comment by jiawulin001** [comment]
@Ovilia  Thank you for guiding me to visual test. However since "Run all test" takes forever to run, I run the test relative to `markArea` and `markLine` and the result is as followed. The first test case is added by me, so it's expected to see differences there and no other test cases are affected.
image

**Comment by Ovilia** [comment]
@jiawulin001 Thanks for running the visual tests! I think you are working with the unexpected test results, right?

> Also it's very time consuming to run all visual tests. It takes 40+ minutes to execute all of them. Is there a way to solve or improve this?

Usually, we only do a thorough test before releasing a new version or the PR changes a lot of logic or the reviewers are not very confident with the changes. For PRs like this, test the files that contain "mark" in their names should be enough. But a thorough test is always helpful so thanks for the effort and time! :)

**Comment by jiawulin001** [comment]
> I think you are working with the unexpected test results, right?

If you mean the issues of `markPoint`, it's been resolved in the update. No other issues occur.

**Comment by plainheart** [comment]
Hi @jiawulin001, Thanks for your recent contributions! They help a lot! It would be better if you could check the reason why the configured `husky` hook and ESLint plugin don't work for you. It can give you on-time corresponding warnings and fixing strategies and reduce extra commits that fix lint issues after you make them work normally. :)

**Comment by jiawulin001** [comment]
My apologies for those lint fix commits! I've been using github desktop to submit commits and the hooks seem not to work on it. I'll use my IDE to submit commits and make sure I execute lint scripts before them in the future. Thank you for your reminding!

**Comment by Ovilia** [comment]
> I have another question regarding visual test. When I am doing all kinds of PR, is there a criterion how I pick what visual tests to do and how should I present the results to the community?

If you want to export the report, there's a "ALL RUNS" button on the menu. Check the versions and time to know which running should be exported and click "report" to export.

**Comment by jiawulin001** [comment]
@Ovilia Hi, I think I've resolved the conflict in merging. Any other suggestions on how should I improve this PR? Or should we move forward to merging?

**Comment by ysldnadotme** [comment]
Hi, Is there any plan to merge the problem to the latest version in the near future? @Ovilia 🤔️

**Comment by Ovilia** [comment]
> Hi, Is there any plan to merge the problem to the latest version in the near future? @Ovilia 🤔️

This PR is scheduled in 5.4.1, which should be published in November.

**Review by Ovilia — APPROVED** [review]
I've run with all test cases and it looks fine.

**Comment by andrius-kurtinaitis** [comment]
It seems this PR breaks zoom functionality: https://github.com/apache/echarts/issues/18099

**Comment by ily-salamat** [comment]
Since version 5.4.1 the markArea in my bar chart is broken, I think it's related to this PR

**Comment by plainheart** [comment]
@ily-salamat Hi, thanks for your report! Please create a new issue and make a reference to this PR. We'll try to confirm and fix it in v5.5.0.

**Comment by plainheart** [comment]
Also, thank you @andrius-kurtinaitis for filing a similar bug. I've marked your issue as high-priority and will fix it first.

**Pull request merged**
