### PR TITLE
fix(label): fix labelLine default style when normal state not show but other state show

### LINKED ISSUE #18680: [Bug] 在使用pie南丁格尔玫瑰图的时候动态隐藏labelLine，线的颜色一直是黑色的，无法使用label颜色
### Version

5.4.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=pie-roseType&version=5.0.0

### Steps to Reproduce

1.demo
官网文档5：https://echarts.apache.org/examples/zh/editor.html?c=pie-roseType&version=5.4.2
官网文档4：https://echarts.apache.org/v4/examples/zh/editor.html?c=pie-roseType
2.描述
在使用pie南丁格尔玫瑰图， 通过emphasis设置饼图label的显示隐藏，线的颜色一直是黑色，在5.x版本黑色显示，在4.x版本是label颜色，
3.我发现通过热更新环境下，我改变的了label隐藏，那么线的颜色会跟随label颜色，但是刷新还是会变成黑色

### Current Behavior

我在实现一个动态显示label,引导线（指示线labelLine）没有跟随color颜色，无法设置labelLine颜色

### Expected Behavior

我期望labelLine颜色跟随color,

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by linghaoSu**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

fix labelLine style not follow label style when normal state  `show: false`, other state `show: true`;

### Fixed issues

- fix #18680

### Before: What was the problem?

when set normal state label show is false, and other state(such as emphasis) state label show: true

labelLine style cannot inherit sector color, and always `#000`

image

### After: How does it behave after the fixing?

although normal state label is show: false, but once any state has show: true, labelStyle will inhreit sector style

image

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — CHANGES_REQUESTED** [review]
The labelLine is not shown as expected [in this case](https://echarts.apache.org/examples/zh/editor.html?version=PR-18800%405b64304&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzJrqzABOE-YJA5AG5aWQDGAhhvQDRnrYAZnVj0hYXv1gEOYDiQDa9AIIgQ2XqIDilDiCwBnTfQAKEaFj3rDxgPK7oeIz1EAhDtA8cjAXTIBfPnQDFhoDRSlUcnIwAE99BhAaSWj0LABbEAALbwhw0lTyDA4AIywMEijC8gMs4AB3EkEuEKlowLai0vKAGXMsSs7o2oaSMEoAVywh2H9OjsLisow-i0Hq2BHG2GaMVsKF1Jk5CI2qjcYuKZIAZhuAViCN2E90gdFVa3oZw8Lz6suGGusBuAEYAAxPDavd70HR6Gw_KGpf6FQHAgBMNwALMjCjCGGYLFZsEYkTNUal0e9QQ88akCaJ7B4nN8Nr8UTN0NSSKD7tiABz06KM-juTyeMnszp-dpkPz-ADcQA). Please have a check.

**Review by Ovilia — CHANGES_REQUESTED** [review]
I think the logic is all right but I'd prefer the way #19180 because `setLabelLineState` is not a frequent operation and thus checking `show` in all states can be ignored. 

However, this PR gives a very solid test for it so I would also like to merge it. Can you revert the changes of `src` and pull & merge from the master and submit again? Thanks!

**Comment by linghaoSu** [comment]
> I think the logic is all right but I'd prefer the way #19180 because `setLabelLineState` is not a frequent operation and thus checking `show` in all states can be ignored.
> 
> However, this PR gives a very solid test for it so I would also like to merge it. Can you revert the changes of `src` and pull & merge from the master and submit again? Thanks!

I apologize for the delayed response. I am pleased to see that the bug has already been resolved, and I am willing to revert the code in the src directory.

**Review by Ovilia — APPROVED** [review]
Thanks for co-author the PR!

**Pull request merged**
