### PR TITLE
fix(pie): Use actual area measure instead of radius in Rose Chart #15674

### PR DESCRIPTION
**Pull request by lulu0119**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

This pull request introduces a new feature that modifies the calculation of the slice radius in the Rose Chart. It addresses the issue mentioned in #15674 by using the square root of the value to accurately represent the data in the visualization.

## Details

|  Before| After|
|  ----  | ----  |
|  60851d1decfa9cf8b14fd08ab00b45b | dc49f5a2228ca171c8b061db51c7f03  |

### Before: What was the problem?

The problem was that the radius of the sectors in the Rose Chart was mapped to the data, which resulted in misleading visualizations. Longer slices received more emphasis due to their larger area size, exaggerating the differences in values.

### After: How does it behave after the fixing?

After the fixing, the slice radius is calculated using the square root of the value. This adjustment ensures that the areas of the slices accurately reflect the data, providing a more consistent and visually accurate representation. The differences in values are now accurately represented without exaggeration.

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — CHANGES_REQUESTED** [review]
Thanks for your contribution. It's nice to see an old feature request being answered.

It seems that you want to name the new feature as `'area'` but this may cause incompatibility problem. So I would suggest not change the behavior of `'area'` while add a new `roseType` value.

Besides, you need to take care of the code with `roseType`. Search it and see if extra code is needed. For example, `if (roseType !== 'area') {` around Line 144 in `pieLayout.ts`. You should probably add your new value name.

Add test cases and run existing pie chart cases to make sure we are not breaking things down. See [the wiki](https://github.com/apache/echarts/wiki/How-to-make-a-pull-request#test) for more information.

**Review by Ovilia — CHANGES_REQUESTED** [review]
I didn't see code changes. Convert to need-modification state.

**Review by Ovilia — CHANGES_REQUESTED** [review]
[Demo](https://echarts.apache.org/examples/zh/editor.html?version=PR-18978%40b6930ed&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzJrqxigkDkARsGJQLbVkC-ANGZcBvQB4lU5WAGcAFsADuJMACcArli4iAZlgCGYBXKxCyIphrkBrIWMkyKirLE4HyBLRoBqELFaQXpsmx1i6GgQA8tAYAJ4kqhoYorb2Iui6opS65hI-1kp2KomiGgBuWACCogCSRnjplr7ZbA716AliWHLuoiQA2g7CidAaTHqw1AByEDjikNA4MbYAwuLGYNS5ImDhIEPUIO4rDklBEAodsJ0ArAAM_gBMlwC6q-QAxvhgrV3UlwCkK8Pf1A99gFgHEACobLbGTR7RKwCBvJgAZXW2H0sPQ9DkBFaACVDscSAAOIHNEROMAaLpA9BeAoxJQkACMV1g_UGNDkINsjOoOWpyFgdIwDNg1xZbK2nLiot5pMStPpQwAzOKBpKubAlbLHiIFcKhgAWVXs4ZS2wG2VAu4NMjWtgAbiAA)

With data

```
data: [
        { value: 10, name: 'rose 1' },
        { value: 20, name: 'rose 2' },
        { value: 30, name: 'rose 3' },
        { value: 40, name: 'rose 4' }
      ]
```

image

Although theoretically it is misleading to use area to represent the value, I also doubt in this case users will think the blue one is half of the green one. But I'm OK to have this feature to give developers another option.

 BTW, this new design should not take the origin name `'area'`. Otherwise, there would be compatible problems. You should give a new name to your design and make sure it doesn't breaks anything down.

**Comment by lulu0119** [comment]
Thank you for your response to my pull request. I agree with your suggestion that the new design should avoid changing the existing name "area" to avoid compatibility issues. Following your advice, I have submitted a commit (20b51db) to fix the issue and named the new design "scaledArea" to avoid conflicts with existing names.

**Review by Ovilia — CHANGES_REQUESTED** [review]
Thanks for your contribution! But I'm afraid I would like to vote against this feature as described in https://github.com/apache/echarts/pull/18978#pullrequestreview-1719598875 . I'm afraid I have to close this PR. If you think the roseType is misleading, I would suggest not using it at all, instead of making the area representing the data. This is because based on previous expriences, users have instincts about how a chart represents data and with roseType or pie charts, it's more the case with angles than area.

**Pull request closed without merging**
