### PR TITLE
feat: allow areaStyle.origin to take number as input

### LINKED ISSUE #16717: [Feature] Area Chart with limit line where area fill is on both sides of mark line.
### What problem does this feature solve?

image

https://echarts.apache.org/examples/en/editor.html?c=area-simple

The area charts we can create and can add markLines which can represent a limit. But here we need to fill the area chart on both sides of the markLine/limit line not the X-Axis.

This is a commonly used type of area chart would be great if we can implement this with ECharts.

### What does the proposed API look like?

I tried [series-line.](https://echarts.apache.org/en/option.html#series-line)[areaStyle.](https://echarts.apache.org/en/option.html#series-line.areaStyle) [origin](https://echarts.apache.org/en/option.html#series-line.areaStyle.origin) = 'auto'

But I couldn't find an API that can fill the area on both sides of the markLine or any horizontal line other than X-Axis.

It would be nice if we have an API/option to set areaStyle on both sides of horizontal line.

### PR DESCRIPTION
**Pull request by jiawulin001**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

Allow `series-line.areaStyle.origin` to take number as input 

### Fixed issues

* Close #16717 

### Before: What was the problem?

The choices for series-line.areaStyle.origin for now is limited to 'start', 'end', and 'auto', which correspond to baseline at bottom, top or axis of the view.

* origin: 'start'
eChIssue#16717-2

* origin: 'end'
eChIssue#16717-3

* origin: 'auto'
eChIssue#16717-1

* And now what is required is to let origin accept a number and set the baseline right at the specified level. Take the picture below as an exmaple.
eChIssue#16717-4

### After: How is it fixed in this PR?

* What is changed in code?
* Here a second `else if` is added to take number in and set it to `valueStart`. NaN is excluded from such situation and will be treated as undefined.
```js
function getValueStart(valueAxis, valueOrigin) {
      var valueStart = 0;
      var extent = valueAxis.scale.getExtent();

      if (valueOrigin === 'start') {
        valueStart = extent[0];
      } else if (valueOrigin === 'end') {
        valueStart = extent[1];
      } // If origin is specified as a number, use it as
      // valueStart directly
      else if (isNumber(valueOrigin) && !isNaN(valueOrigin)) {
          valueStart = valueOrigin;
        } // auto
        else {
            // Both positive
            if (extent[0] > 0) {
              valueStart = extent[0];
            } // Both negative
            else if (extent[1] < 0) {
                valueStart = extent[1];
              } // If is one positive, and one negative, onZero shall be true

          }

      return valueStart;
    }
```
* An example of using number as `areaStyle.origin`
eChIssue#16717-6

## Misc

- [x] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

- **The echarts-doc has not been changed yet, I can submit another PR to update the doc.**

### CODE REVIEW

**Comment by pissang** [comment]
@jiawulin001 Wow looks great!

BTW do you mind adding a test case?

**Comment by jiawulin001** [comment]
yes, I can add a test case

**Comment by jiawulin001** [comment]
Any suggestion on which test.ts to add the test case to? I didn't find any existent test file that includes areaStyle, so my plan is to add a new test file under test/ut/spec/series. Is that OK?

**Comment by pissang** [comment]
@jiawulin001 We usually add test cases in the test folder. Run `npm run mktest area-origin` and it will generate a template for you.

**Comment by jiawulin001** [comment]
@pissang Hi, the test case has been added. Check it out!

**Review by pissang — APPROVED** [review]

**Comment by plainheart** [comment]
Hi @jiawulin001, thanks for your contribution to this new feature and this is just a reminder. Are you working on adding or planning to add this new area origin value for the line series in the documentation?

**Comment by jiawulin001** [comment]
@plainheart Oh yes, thank you for your reminding! The PR for updating documentation has been submitted.

**Pull request merged**
