### PR TITLE
fix: bug 16849

### PR DESCRIPTION
**Pull request by Ling310**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

- Close https://github.com/apache/echarts/issues/16849

### Fixed issues
https://github.com/apache/echarts/issues/16849

### Before: What was the problem?
dataZoom.borderColor not work
image

### After: How is it fixed in this PR?

dataZoom.borderColor work

image

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by plainheart — APPROVED** [review]
Good catch! I checked the minimized script and found it was correctly compressed. It might be because your bundler or minimizer can't handle such a comment. Anyway, this kind of inline comment is not very regular in my view. It should be `/* COMMENT */` at least.

**Comment by plainheart** [comment]
Just found it may be confusing if we put this comment on this line? Could you please move it to the previous line?

**Comment by Ling310** [comment]
ok,I will remove this comment，and make a new PR

**Comment by pissang** [comment]
@Ling310 No need to create a new PR. Just push a commit to fix it.

**Comment by Ling310** [comment]
changed: 1b9afd847a58d7b48adbab8d2273c9f30e8521d4

**Review by plainheart — APPROVED** [review]

**Pull request merged**
