### PR TITLE
chore: start a local server for testing when run dev #17868

### PR DESCRIPTION
**Pull request by Ovilia**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

Start a local server when run `npm run dev` and update the README. Hopefully, this can better help new contributors to get started.

### Fixed issues

#17868

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by plainheart — COMMENTED** [review]
There are two problems with this command,

1. The former command may block the latter command.
2. It's not enough to only serve the `test` folder as the test case requires some external resources, such as `dist` and `node_modules`.

So I would like to suggest using the following command,

```shell
npx concurrently \"npm run dev:fast\" \"npx http-server -c-1 -s -o test\"
```

That is, serve the project root folder and open the `test` folder automatically.

`-c-1` is to disable the cache.
`-s` is to make the server silent and no access logs. It's optional. Do you think it's good to add that?

**Comment by Ovilia** [comment]
> The former command may block the latter command.

It doesn't seem to be blocked to me. Can you give a more detailed explanation? In my environment, `Bundled with esbuild` is printed after the command and it prints again on file changes in `src`.

`npx concurrently` gives extra prompt for developers to confirm so I think if it works without concurrently, it would be better:

```sh
Need to install the following packages:
  concurrently@7.5.0
Ok to proceed? (y)
```

And there are other problems with your suggestion:

```sh
[0] /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
[0] /bin/sh: -c: line 1: syntax error: unexpected end of file
[1] /bin/sh: run: command not found
[0] "npm exited with code 2
[2] /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
[2] /bin/sh: -c: line 1: syntax error: unexpected end of file
[1] run exited with code 127
[2] dev:fast" exited with code 2
[3] /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
[3] /bin/sh: -c: line 1: syntax error: unexpected end of file
[3] "npx exited with code 2
```

I'm using Bash on Mac terminal.

**Comment by Ovilia** [comment]
It seems Windows and Mac shell have some differences. @plainheart 's suggestions works well in `scripts` in `package.json` so I used this command. Thanks!

**Comment by plainheart** [comment]
> npx `concurrently` gives extra prompt for developers to confirm so I think if it works without concurrently, it would be better:

Thanks for accepting the suggestion! Maybe we can pass `-y` to `npx` to avoid the installation tip.

**Review by plainheart — APPROVED** [review]
LGTM

**Comment by AntiMoron** [comment]
Thanks @Ovilia 

That's why echarts' better than other Chinese open source softwares.

**Pull request merged**
