### PR TITLE
italian version

### PR DESCRIPTION
**Pull request by napo**
added the italian version

## Brief Information
I just added the italian translation

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

Now the users can switch the language in italian

## Document Info

One of the following should be checked.

- [X] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by plainheart** [comment]
Hi @napo, thanks for your contribution to i18n! You only need to add the Italian language file to the [`src/i18n`](https://github.com/apache/echarts/tree/master/src/i18n) folder. Please refer to the changes in #17244.

**Comment by plainheart** [comment]
It seems the Italian language file has been submitted. You can edit the following file if you hope to correct something.

https://github.com/apache/echarts/blob/master/src/i18n/langIT.ts

**Comment by napo** [comment]
@plainheart  Thanks a lot! Ill' proceed

**Comment by plainheart** [comment]
@napo Hi, I'd like to know if you are working or planning to work on this?

**Comment by plainheart** [comment]
I'm sorry to close this PR as it is not active for some time and there is no response from the author.

**Pull request closed without merging**
