### PR TITLE
fix(bar): fix bar chart bars overflowing the coordinate system

### LINKED ISSUE #19972: [Bug] Bar Chart bars overflow out of the coordinate system
### Version

5.5.0

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurALYTREBMANCemQIYZEBsAdNSQL73oBzAE4QAJkVSlYAGwCmAMzBEAjAAZV_UiIEALJbDWremgJ458EviTyyRswrADaDYlPTQmZWUQDkAZSY5H00pMBMQb1gfACMmIWCXdFEmMCYiZzdSR2VaWABWAF0Qt0c6WGpVIsSsgGZcmrYqzPRHABZctSbmxzyOyuKpRzZciq7MxwB2XNaC6rHSAGNpCBAiMCEAV1kXHhJZngBuIA

### Steps to Reproduce

Open the minimal reproduction link and you should easily see the issue.

### Current Behavior

The [clip option](https://echarts.apache.org/en/option.html#series-bar.clip) for bar chart doesn't work as expected.

image

### Expected Behavior

It should look like this when clip option is true.

image

### Environment

```markdown
The environment is irrelevant but here it is:

- OS: macOS Sonoma
- Browser: Chrome 125
```

### Any additional comments?

The option was actually working as expected, but at some point it was broken, specifically by #11338. The PR seems intentional. But there is no explanation on why it is done or any link to any existing issues. I assume author did it for a specific use-case, but they could have easily used `clip: false` to achieve the same result.

Here are some related issues:

#17858
#12720
#13321
#11240
#10374

I am working on a PR to fix this.

### PR DESCRIPTION
**Pull request by KurtGokhan**
## Brief Information

This pull request is in the type of:

- [x] bug fixing

### What does this PR do?

[Bar chart clip option](https://echarts.apache.org/en/option.html#series-bar.clip) now clips the bar at the edges of the coordinate system so that it doesn't overflow.

### Fixed issues

Fixes #19972

## Details

See #19972 for detailed info and additional links.

### Before: What was the problem?

See [example](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurALYTREBMANCemQIYZEBsAdNSQL73oBzAE4QAJkVSlYAGwCmAMzBEAjAAZV_UiIEALJbDWremgJ458EviTyyRswrADaDYlPTQmZWUQDkAZSY5H00pMBMQb1gfACMmIWCXdFEmMCYiZzdSR2VaWABWAF0Qt0c6WGpVIsSsgGZcmrYqzPRHABZctSbmxzyOyuKpRzZciq7MxwB2XNaC6rHSAGNpCBAiMCEAV1kXHhJZngBuIA)

image

### After: How does it behave after the fixing?

`bar-clip` test covers this case.

image

There is also a test with `dataZoom.filterMode:'none'`

image

## Document Info

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### Other information

Here is the diff

image

### CODE REVIEW

**Comment by admsev** [comment]
@gooroodev review

**Comment by gooroodev** [comment]
### 1. Summary of Changes

This pull request addresses an issue where bar chart bars overflow the coordinate system. The changes include:
- Modifying the condition in the `getClipArea` function within `BarView.ts` to correctly handle bar clipping for category axes.
- Adding a new test file `bar-clip.html` to verify that bar charts do not overflow the coordinate system under different conditions (such as setting `min` and `max` values on the x-axis and using `dataZoom`).

### 2. Issues, Bugs, or Typos

#### Code Issues
1. **Condition Change in `BarView.ts`**:
   - The condition change in `BarView.ts` seems logical, but it would be prudent to ensure that this change does not introduce any regressions for other axis types.

2. **Test File `bar-clip.html`**:
   - The test file is comprehensive; however, it lacks assertions to automatically verify the correctness of the output. Currently, it relies on visual inspection.

#### Proposed Improvements

1. **Adding Assertions in Test File**:
   - To improve the robustness of the test, consider adding automated assertions that verify the bars do not overflow the coordinate system. This can be done using a testing framework that supports DOM assertions.

### 3. General Review of Code Quality and Style

#### Code Quality
- **Readability**: The code is generally readable and well-commented. The comments in `BarView.ts` provide context for the changes.
- **Modularity**: The changes are modular and localized to specific functions and test files, making it easier to review and understand the impact.

#### Style
- **Consistency**: The coding style is consistent with existing code, following the project's conventions.
- **Documentation**: The new test file includes a detailed license header, which is good practice.

### Suggested Code Improvements

1. **Automated Assertions in Test File**:
   ```javascript
   <script>
   require([
       'echarts',
   ], function (echarts) {
       var option;

       option = {
           xAxis: {
               min: 2,
               max: 6.2,
           },
           grid: {
               left: 100,
               right: 100,
           },
           yAxis: {},
           series: [{
               name: "Sale",
               type: "bar",
               data: [[1,5], [2,20], [3,36], [4,10], [5,10], [6,20], [7,4]],
               clip: true,
           }],
       };

       var chart = testHelper.create(echarts, 'main0', {
           title: [
               'Bar Chart should not overflow with min/max',
               'See issue #19972',
           ],
           option: option
       });

       // Automated assertion example
       var chartInstance = echarts.getInstanceByDom(document.getElementById('main0'));
       var seriesModel = chartInstance.getModel().getSeriesByIndex(0);
       var data = seriesModel.getData();
       var coordSys = seriesModel.coordinateSystem;

       data.each(function (idx) {
           var layout = data.getItemLayout(idx);
           var x = layout.x;
           var width = layout.width;
           if (x < coordSys.getRect().x || (x + width) > (coordSys.getRect().x + coordSys.getRect().width)) {
               console.error('Bar is overflowing the coordinate system at index:', idx);
           }
       });
   });
   </script>
   ```

2. **Unit Tests for `getClipArea` Function**:
   - Consider adding unit tests for the `getClipArea` function to ensure that the new condition handles all edge cases correctly.

### Conclusion

The pull request effectively addresses the issue of bar chart bars overflowing the coordinate system. Adding automated assertions in the test file and unit tests for the `getClipArea` function would further enhance the robustness and reliability of the solution. Overall, the code quality and style are commendable, adhering to project conventions and ensuring readability.

Yours, [Gooroo.dev](https://gooroo.dev). To receive reviews automatically, [install Github App](https://github.com/apps/gooroo-dev)

**Review by Ovilia — CHANGES_REQUESTED** [review]
This is a highly anticipated feature that has been requested by multiple users, so it's exciting to see this pull request.

Let's first clarify the behavior.

## Without dataZoom

When dataZoom is not used, this pull request introduces a breaking change for bar series. According to the [documentation](https://echarts.apache.org/en/option.html#series-bar.clip), `clip: true` means: "Clip all the overflowed. With bar width kept." Therefore, we cannot consider the previous behavior a bug.

> `Bar: Clip all the overflowed. With bar width kept.`
> The English documentation might be a bit unclear. The Chinese version specifies that the bars are not clipped.

### Recommendation

We can either:

1. Maintain the behavior of `clip: true` and introduce another option like `clipMode` or string values for `clip: 'xxx'`. While this may not be the perfect default solution, it does provide developers with a method to achieve their desired outcomes.
2. Clip bars outside the grid as the current implementation does, and introduce this breaking change in ECharts 6.0, which is expected to be released early next year. Special attention should be given to cases with a category axis with `boundaryGap: false`, where the axis should shrink to ensure it won't be clipped. See the images below for reference.

**Current Behavior**

If we clip the bars as shown in the image below, the first and last bar will have half width, which is not expected.

image

**Expected Behavior**

If the axis can be shrunk and the grid width remains unchanged as shown below, then it won't be affected when clipped.

image

As illustrated, solution 2 requires more effort for you but has the potential to be more intuitive. Therefore, you may want to consider which approach we should take.

## With dataZoom

If no breaking changes are considered, bars should never be clipped because neither `clip: true` nor any value of `filterMode` will result in the expected clipping behavior. If breaking changes are considered, please refer to the above notes on solution 2.

**Comment by Ovilia** [comment]
@KurtGokhan Here is an [example](https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurALYTRECMADAJwkC-ANCQJ475GqmxjsQAUyIByAG4BDADYBXIaOZt0AcwBOEACY8S6aUIBmYIgGYArLSUk8QjUMKwA2ruJ90myWElFH1AEy0LLDUFkEAHIGwAOyR1HRB1Ca0ALrKbgLCYgBGkmqiaXwAxtIQIEQGMjYuTCTJKEwA3EA)

```ts
option = {
  xAxis: {
    min: 109
  },
  yAxis: {
    type: 'value'
  },
  grid: {
    left: 350
  },
  series: [
    {
      data: [120, 150, 80, 70, 110, 130],
      type: 'bar',
      clip: false
    }
  ]
};
```

image

I agree with the saying that it's more intuitive to hide the two bars outside of the grid area. But for the bar at `110`, it may be controversial whether or not to clip that part outside of the grid.

**Comment by KurtGokhan** [comment]
@Ovilia I see. What do you suggest? Maybe we can introduce a `clip: 'strict'` option in addition to `true/false`. For bar chart, it would work like I did in this PR, and for other charts it would work like `true`.

**Comment by Ovilia** [comment]
> @Ovilia I see. What do you suggest? Maybe we can introduce a `clip: 'strict'` option in addition to `true/false`. For bar chart, it would work like I did in this PR, and for other charts it would work like `true`.

I'm making a [breaking axis](https://github.com/apache/echarts/pull/19459) feature for ECharts 6.0 where bars get clipped by default. But I'm still working on it and not sure at this moment what it will ended up to be. I need to consider more carefully on this when I do with breaking axis, which may probably take another few months. So do you mind if we close this PR for now and see how it goes?

**Comment by KurtGokhan** [comment]
@Ovilia  ok, we can close this. But I need a fix for now because the bar chart clipping with the axis labels seems too wrong: 
image

I tried using a custom series. But I couldn't figure out how to do stacked bars with custom series. Any tips or resources you can guide me for doing that?

**Comment by Ovilia** [comment]
Do you want to clip the left-most and right-most bars, or is [this](https://echarts.apache.org/examples/zh/editor.html?c=bar-simple&code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXMmurADYCmAZmIQIwCsADMQL4A0xAHgIKcQDOhVCVhgAniHKEA5AGMAhmHIZgWMdI4jci-YQDa0gLIwNsaQBUAruVPSA6uVy3zAC0u2AYjlsBlRb8toaQBdTRIAI2BA7TUAcXkQQkp5Un5yVjCxXgEhYnRxSRkANxTrDTzYeT5-ABl5cPJSXJF0AHc8MBdCACZGRjCREHlcXAhoDH1-2AAWKbngipYM4jScckFYPQrhFu0wXU3aXrZYXqmGKYAOKYB2c9pzgGZGUIr8iSkzcPksaUXiBYsADcQA) acceptable?

**Comment by KurtGokhan** [comment]
Yes, I don't want the bars to go out of the grid. I also want it to work reliably with any axis type, i.e. time.

**Comment by Ovilia** [comment]
Then I think custom series is a must. It would be challenging to implement stacking, but since stacking on time axis is also not supported for bar series, using custom series seems to be the only possible solution.

**Comment by KurtGokhan** [comment]
> Stacking on time axis is also not supported for bar series

It is supported and I am using it. The only limitation is that all series must have uniform data.

**Comment by Ovilia** [comment]
Yes, it's supported, sorry I forgot. If you have no objection, perhaps we could close this PR and I will see what we can do when I complete the break axis feature.

**Comment by KurtGokhan** [comment]
Tbh, my problem isn't solved. And I don't see how "breaking axes" solves the problem. But you can close the PR.

**Comment by grenobnik** [comment]
It is a pity that this PR is closed without further development. I also need to clip the stacked bars to the grid. The proposed "strict" value for `clip` option sounds like a reasonable solution to not introduce the breaking changes.

**Review by mazoqui — COMMENTED** [review]
It still does no fix the issue, whether a background is set to the bar serie.
A workaround would requires you to also clip the bar background in the edges and make opaque when far of them, something like below:


```
.update(function (newIndex, oldIndex) {
                var itemModel = data.getItemModel(newIndex);
                var layout = getLayout[coord.type](data, newIndex, itemModel);
                if (drawBackground) {
                    var isClipped = clip[coord.type](coordSysClipArea, layout);
                    var bgEl;
                    var bgSt;
                    var diff;
                    if (oldBgEls.length === 0) {
                        bgEl = createBackground(oldIndex);
                    }
                    else {
                        bgEl = oldBgEls[oldIndex];
                        bgSt = backgroundModel.getBarItemStyle();
                        if (isClipped) {
                            bgSt.opacity = 0;
                        }
                        bgEl.useStyle(bgSt);
                        // Only cartesian2d support borderRadius.
                        if (coord.type === 'cartesian2d') {
                            bgEl.setShape('r', barBorderRadius);
                        }
                        bgEls[newIndex] = bgEl;
                    }
                    var bgLayout = getLayout[coord.type](data, newIndex);
                    var shape = createBackgroundShape(isHorizontalOrRadial, bgLayout, coord);
                    if (coord.type === 'cartesian2d') {
                        if (shape.x < coordSysClipArea.x) {
                            diff = coordSysClipArea.x - shape.x;
                            shape.x += diff;
                            shape.width -= diff;
                        }
                        else if ((shape.x + shape.width) > (coordSysClipArea.x + coordSysClipArea.width)) {
                            diff = (shape.x + shape.width) - (coordSysClipArea.x + coordSysClipArea.width);
                            shape.width -= diff;
                        }
                    }
                    updateProps(bgEl, { shape: shape }, animationModel, newIndex);
                }
                var el = oldData.getItemGraphicEl(oldIndex);
                if (!data.hasValue(newIndex)) {
                    group.remove(el);
                    return;
                }

                if (needsClip) {
                    var isClipped = clip[coord.type](coordSysClipArea, layout);
                    if (isClipped) {
                        group.remove(el);
                        return;
                    }
                }
....
```

**Pull request closed without merging**
