### PR TITLE
feat(LineDraw):series-lines support the effect animation go back

### PR DESCRIPTION
**Pull request by wangguisong**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

add the effect.goback property in series-lines to enable the effect animation can go back to the starting point after reaching the destination. it`s necessary to indicates a round trip flight.

### Before: What was the problem?

the effect animation in series-lines is one-way, can not indicates a round trip flight.

one-way

### After: How is it fixed in this PR?

add the effect.goback property in series-lines to enable the effect animation can go back

goback

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by pissang** [comment]
Looks great! Could we rename the option from `goback` to `roundTrip` to be more meaningful?

**Comment by wangguisong** [comment]
> Wow looks great! Could we rename the option from `goback` to `roundTrip` to be more meaningful?

yes, of cause

**Review by pissang — APPROVED** [review]

**Comment by Ovilia** [comment]
This PR seems to be released in 5.3.3 but is missing from the [5.3.3 changelog](https://github.com/apache/echarts/releases/tag/5.3.3).

**Comment by cr0032** [comment]
解决了吗

**Pull request merged**
