### PR TITLE
fix(labelLine):emphasis.labelLine not work in pie chart

### PR DESCRIPTION
**Pull request by shiersansi**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

solved problem:emphasis.labelLine not work in pie chart #19160

### Fixed issues

[https://github.com/apache/echarts/issues/19160](url)
#19160

### Before: What was the problem?
label lines are not hidden when emphasis

### After: How does it behave after the fixing?
When I select the blue section,label lines  are hidden when emphasis

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by Ovilia** [comment]
Please fix the failed test case in the CI and run [visual tests](https://github.com/apache/echarts/wiki/How-to-make-a-pull-request#run-test-cases) of all cases to make sure it doesn't break any changes. Please also note that #18800 was also trying to fix the same problem. The first PR that finds the correct solution will be merged. Thanks!

**Review by Ovilia — CHANGES_REQUESTED** [review]
Please fix the failed test case in the CI and run [visual tests](https://github.com/apache/echarts/wiki/How-to-make-a-pull-request#run-test-cases) of all cases to make sure it doesn't break any changes. Please also note that https://github.com/apache/echarts/pull/18800 was also trying to fix the same problem. The first PR that finds the correct solution will be merged. Thanks!

**Review by Ovilia — CHANGES_REQUESTED** [review]
Please fix the lint problems and [this demo](https://echarts.apache.org/examples/zh/editor.html?version=PR-19180%40c984f16&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzJrqzABOE-YJA5AG5aWQDGAhhvQDRnrYAZnVj0hYXv1gEOYDiQDa9AIIgQ2XqIDilDiCwBnTfQAKEaFj3rDxgPK7oeIz1EAhDtA8cjAXTIBfPnQDFhoDRSlUcnIwAE99BhAaSWj0LABbEAALbwhw0lTyDA4AIywMEijC8gMs4AB3EkEuEKlowLai0vKAGXMsSs7o2oaSMEoAVywh2H9OjsLisow-i0Hq2BHG2GaMVsKF1Jk5CI2qjcYuKZIAZhuAViCN2E90gdFVa3oZw8Lz6suGGusBuAEYAAxPDavd70HR6Gw_KGpf6FQHAgBMNwALMjCjCGGYLFZsEYkTNUal0e9QQ88akCaJ7B4nN8Nr8UTN0NSSKD7tiABz06KM-juTyeMnszp-dpkPz-ADcQA) also fails.

**Comment by shiersansi** [comment]
> Please fix the lint problems and [this demo](https://echarts.apache.org/examples/zh/editor.html?version=PR-19180%40c984f16&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzJrqzABOE-YJA5AG5aWQDGAhhvQDRnrYAZnVj0hYXv1gEOYDiQDa9AIIgQ2XqIDilDiCwBnTfQAKEaFj3rDxgPK7oeIz1EAhDtA8cjAXTIBfPnQDFhoDRSlUcnIwAE99BhAaSWj0LABbEAALbwhw0lTyDA4AIywMEijC8gMs4AB3EkEuEKlowLai0vKAGXMsSs7o2oaSMEoAVywh2H9OjsLisow-i0Hq2BHG2GaMVsKF1Jk5CI2qjcYuKZIAZhuAViCN2E90gdFVa3oZw8Lz6suGGusBuAEYAAxPDavd70HR6Gw_KGpf6FQHAgBMNwALMjCjCGGYLFZsEYkTNUal0e9QQ88akCaJ7B4nN8Nr8UTN0NSSKD7tiABz06KM-juTyeMnszp-dpkPz-ADcQA) also fails.

In this section of the code comment, it is mentioned that if label is false, labelLine will not be displayed. So, should we modify it to mean that lableLine will not be affected no matter what the label is

**Review by Ovilia — APPROVED** [review]

**Pull request merged**
