### PR TITLE
legend.data.icon  Add dashed

### PR DESCRIPTION
**Pull request by cuijian-dexter**
add dashed style
```
legend:{
       data: [
        {
            icon: 'dashed'
        }]
}
```

### CODE REVIEW

**Comment by cuijian-dexter** [comment]
#9552

**Comment by Ovilia** [comment]
Thanks for your contribution.
But I don't think dash should be a new shape. Instead, I think it should be a property of style for a line shape. Legend item needs to be improved, not only line dash, but also stroke color, stroke width, and so on to make better understanding of series.
@100pah Would you agree on this?

**Comment by jadugman** [comment]
Thanks

**Comment by JJZolper** [comment]
This nearing completion? There's also this other [item](https://github.com/apache/incubator-echarts/issues/9552).

**Comment by JJZolper** [comment]
My client is asking for this and besides trying to get wild with an image it'd be nice if we could get movement on a real solution.

**Pull request closed without merging**
