### PR TITLE
test: add map test for optimizing small regions.

### PR DESCRIPTION
**Pull request by pissang**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

1. add map test for optimizing small regions
2. add new china map
3. update zrender version
4. fix type issues after change in https://github.com/ecomfe/zrender/pull/759/files

### CODE REVIEW

**Review by plainheart — COMMENTED** [review]
In export/core.ts, do we need to export `ImagePatternObject` & `SVGOatternObject`?
https://github.com/apache/echarts/blob/master/src/export/core.ts#L29

**Comment by pissang** [comment]
@plainheart Do you mean we only need to export ImagePatternObject?

**Comment by plainheart** [comment]
Why not export these three types: `PatternObject`, `ImagePatternObject` & `SVGPatternObject`?

**Comment by pissang** [comment]
@plainheart Understand, good idea.

**Comment by pissang** [comment]
@plainheart Added

**Review by plainheart — APPROVED** [review]

**Pull request merged**
