### PR TITLE
add valueFormatter in tooltip

### PR DESCRIPTION
**Pull request by pissang**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

This PR added a new option `valueFormatter`. It's the most commonly used formatter scenario we've met. See more detail in https://github.com/apache/echarts/issues/14962

#### API

```ts
interface valueFormatter {
  (value: number | string | (string | number)[]) => string
}
```

Parameter `value` is the number or string(category) that displayed in each row. For example, in the following tooltip:

Each row will call the `valueFormatter` once and the value will be `0.3`, `12.71`, `0` respectively.

NOTE: `valueFormatter` will take no effect if `formatter` is used.

### Fixed issues

https://github.com/apache/echarts/issues/14962
https://github.com/apache/echarts/issues/15430

### Before: What was the problem?

We need to replace the whole HTML with formatter if we only want format the numbers.

### After: How is it fixed in this PR?

Use `valueFormatter` to only format the numbers.

## Misc

- [x] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Basic usage: adding %

```ts
tooltip: {
    position: 'top',
    valueFormatter: (val) => val + '%'
},
```

### Using different formatter in different series.

```ts
series: [{
    name: 'CPU',
    type: 'line',
    showSymbol: false,
    tooltip: {
        valueFormatter: (value) => value + ' %'
    },
    ...
}, {
    name: 'RAM',
    type: 'line',
    yAxisIndex: 1,
    tooltip: {
        valueFormatter: (value) => value + ' MB'
    }
    ...
}
```

148333759-ec875352-8ecc-4a64-a109-6d977021578e

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by plainheart** [comment]
What if we set a `valueFormatter` for the global tooltip? Should the `valueFormatter` callback include all the series values? the first argument in `formatter` callback will include all the series values. But it seems the current `valueFormatter` includes only one series value.

**Comment by pissang** [comment]
@plainheart Because formatter is for the whole tooltip. It returns one HTML string for the tooltip. And `valueFormatter` will be called for each value. It's also returns one string after formatted. It's more consistent and easier for developer to process. 

If we return an array. Developers need to check if value is array and loop them to process each one. And they may be confused if they should return an array or a combined string.

There are cases that different series need to have different formatted result. The `series.tooltip.formatter` metioned in the description exists for this situation. We can also add a second param that includes `seriesIndex`, `dataIndex` for more information. It's like callback in `xAxis.axisLabel.formatter`. But I prefer to keep it simple at first.

**Review by plainheart — APPROVED** [review]
Well. LGTM.

**Comment by crazyair** [comment]
等发正式版，刚试了下 rc，控制台一堆报错。

**Comment by susiwen8** [comment]
@crazyair 能提供下复现示例吗？

**Comment by crazyair** [comment]
> @crazyair 能提供下复现示例吗？

https://codesandbox.io/s/funny-volhard-mclm9?file=/src/index.js  先看看这个示例，配置了 valueFormatter 没效果

**Comment by crazyair** [comment]
> @crazyair 能提供下复现示例吗？

image

**Comment by susiwen8** [comment]
> > @crazyair 能提供下复现示例吗？
> 
> image

这个能提供最小复现示例吗？

**Comment by pissang** [comment]
@crazyair 看了下报错信息，可能是渐变色动画引起的，可以检查下配置项中的渐变色配置是否有使用非法的颜色字符串（无法被解析的）

**Comment by crazyair** [comment]
> @crazyair 看了下报错信息，可能是渐变色动画引起的，可以检查下配置项中的渐变色配置是否有使用非法的颜色字符串（无法被解析的）

对，是使用了渐变色，由于示例死循环了非常卡，渐变色我是这样配置的
```
_options = {
            tooltip: { trigger: 'axis' },
            grid: { left: 5, right: 5, bottom: 5, top: 5 },
            xAxis: [
                {
                    show: false,
                    type: 'category',
                    boundaryGap: false,
                },
            ],
            yAxis: [{ show: false, type: 'value' }],
            series: [
                {
                    type: 'line',
                    smooth: true,
                    lineStyle: { width: 2 },
                    showSymbol: false,
                    areaStyle: {
                        opacity: 0.2,
                        color: new graphic.LinearGradient(0, 0, 0, 1, [
                            { offset: 0, color: `${get(options, ['color', 0])}` },
                            { offset: 1, color: 'rgb(255, 255, 255)' },
                        ]),
                    },
                },
            ],
        };
```
起始 color 是 options.color[0] 的值 rgb(220 221 251)

**Comment by crazyair** [comment]
> @crazyair 能提供下复现示例吗？

https://codesandbox.io/s/pensive-cloud-f8n8b?file=/src/index.js

**Comment by crazyair** [comment]
> @crazyair 能提供下复现示例吗？

https://codesandbox.io/s/pensive-cloud-f8n8b?file=/src/index.js

**Comment by plainheart** [comment]
rgb 的逗号呢？还是用法不规范啊...

**Comment by crazyair** [comment]
> rgb 的逗号呢？还是用法不规范啊...

尴尬，眼花了，vscode 在这里会有背景色，没看到有没有逗号

**Comment by AN-535** [comment]
image
好像valueFormatter无效

**Comment by plainheart** [comment]
可能是缓存，清一下缓存刷新再试。

**Comment by AN-535** [comment]
> 

感谢，强制刷新后解决了

**Comment by Cat1007** [comment]
后续可以添加dataIndex吗

**Pull request merged**
