### PR TITLE
style: spelling mistakes

### PR DESCRIPTION
**Pull request by ZXYT**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

fix word spelling mistakes

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — CHANGES_REQUESTED** [review]
MarkLineView also have similar problem. Can you also help change them? Thanks!

**Comment by ZXYT** [comment]
什么问题呀 羡辙小姐姐🤣

**Comment by ZXYT** [comment]
ok👌

**Review by plainheart — APPROVED** [review]

**Comment by pissang** [comment]
pin @Ovilia to check this PR again.

**Review by Ovilia — APPROVED** [review]

**Pull request merged**
