### PR TITLE
feat(funnel): new funnel style

### PR DESCRIPTION
**Pull request by susiwen8**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

The shape of the last piece of funnel should be rect.

### Fixed issues

- #12937 Can't close, cause the second one isn't inclued in this PR

### Before: What was the problem?

Screen Shot 2022-05-24 at 11 09 26 PM
Screen Shot 2022-05-24 at 11 09 42 PM

### After: How is it fixed in this PR?

Screen Shot 2022-05-24 at 11 04 08 PM
Screen Shot 2022-05-24 at 11 04 23 PM

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by tyn1998** [comment]
Haha, I think part of [the project](https://summer-ospp.ac.cn/#/org/prodetail/22ffc0288) listed in OSPP Summer 2022 is resolved.

**Comment by susiwen8** [comment]
Haha, my mistake

**Comment by pe-2** [comment]
Why are the last two labels out of place？For me, an ocD, It's too uncomfortable.😂

**Comment by tyn1998** [comment]
Hi @pe-2~

Maybe @susiwen8 set the option on purpose to test [different label positions](https://echarts.apache.org/zh/option.html#series-funnel.label), I suppose?

**Comment by pe-2** [comment]
I got it. 😂

**Comment by mfbaltaza** [comment]
How do I make the chart horizontal?

**Pull request closed without merging**
