### PR TITLE
the exceptiom prevents cicd running

### PR DESCRIPTION
**Pull request by DominiqueDeCordova**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

Removes the code which throws an exception

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — COMMENTED** [review]
Hi, this code should probably not be removed. If you meet with errors throw by it, you should probably check your option to make sure corresponding mistakes are taken care of.

**Comment by DominiqueDeCordova** [comment]
Thank you for the comment.

As far as I see, the code throws an exception in DEV mode, but does not throw an exception in Production. That allows us to deploy to Production, but prevents using CICD.

My request is to make the code uniform: if in one environment the code does not throw an exception, it should not do it in another.
I would appreciate your consideration,
Dmitriy

**Comment by pissang** [comment]
@DominiqueDeCordova You can change it to logging error message and render nothing instead of throwing a error.

**Comment by kriewall** [comment]
@pissang I work with @DominiqueDeCordova on the same project.  I think there is some misunderstanding.  First of all, the issue has nothing to do with CICD.  The problem is that heatmap plotting bombs out only in a dev environment if two category axes are not provided, whereas it works fine under any other environment.  The behavior we're getting out of the heat map works exactly as desired in a non-dev environment; it also works just fine if we create a custom environment that fakes a non-dev environment.  But all this creates unnecessary overhead just to bypass an exception thrown by eCharts only if you happen to be working in a dev env.  

To be clear, we do not want eCharts to render nothing.  We want it to render the same in a dev env as it does in other environments.

Am I missing something?  What is the design intent behind bypassing perfectly functional behavior and instead throwing an exception, and additionally inducing different behavior across environments?

**Review by andrewchoi5 — APPROVED** [review]

**Review by kriewall — APPROVED** [review]

**Comment by Ovilia** [comment]
Sorry for late reply. These error logs don't exist for no reason. Heatmap supports only when both axes are category type. Not giving an error doesn't mean it work but that we try not to break down things in the production mode. Sorry you have to do some hacking in your environment to meet with your requirement. I am going to close this PR but thanks for your contribution any way!

**Pull request closed without merging**
