### PR TITLE
fix: eslint

### PR DESCRIPTION
**Pull request by h7ml**
## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

#### fix action lint
image
image

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

``pnpm lint``

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by h7ml** [comment]
## Deleted the code that was introduced but not used in the code as follows
1. [BoxplotSeriesModel](https://github.com/apache/echarts/pull/17147/files#diff-ebc0d26bc0f700b8374adf54cfca30189cd780a4e3b48acaa7eb7220ebc842e2L22)
2. [SunburstSeriesNodeItemOption](https://github.com/apache/echarts/pull/17147/files#diff-2e4a828a366e05a52c1a1b52b9eae9412190e9f343b313465aeff82174564a3aR24)
3. [TreemapSeriesOption](https://github.com/apache/echarts/pull/17147/files#diff-f3d866579b39927bb1e154fd3c6b5a5146aa36eeb169b8c4697a6ecee41178d7L22)
4. [GetPieceValueType](https://github.com/apache/echarts/pull/17147/files#diff-52d0c614050f6d45fac915e98b35e86031de8ad0e1f8eda443d154e99527567eL47)

**Comment by Ovilia** [comment]
Thanks for the changing! Did you use some auto formatting tools (like prettier) or manually changed this?

**Comment by h7ml** [comment]
> Thanks for the changing! Did you use some auto formatting tools (like prettier) or manually changed this?

Yes, I do use the auto format tool, I use the prettier that comes with vscode

**Comment by h7ml** [comment]
In [the action lint] (https://github.com/apache/echarts/actions/runs/2420710373),
image
image
There is always an issue with not being able to pass Lint, maybe you should pay attention to this

**Comment by h7ml** [comment]
Consider using `` tslint+prettier+husky+lint-staged`` code formatting specification guarantees

**Comment by Ovilia** [comment]
Thanks for the suggestion. I think the main problem we need to decide is what to do with the old stylings. Please continue the discusstion in [the mailing list](https://lists.apache.org/thread/kt4s7tjxk512qh4ysp1dw1cov4r7qqkj). I would like to close this PR if you are OK with that.

**Pull request closed without merging**
