### PR TITLE
feat(state): add emphasis.disabled

### PR DESCRIPTION
**Pull request by pissang**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

Introduce `emphasis.disabled` to disable emphasis state on hover and tooltip trigger. `Previously` we can only use `silent` to disable any hover interactions. But it will also lost the mouse event.

By disabling `emphasis` state. We can avoid potential performance issue when interacting with massive data like in https://github.com/apache/echarts/issues/16133 . Or remove unwanted highlight / emphasis effect like in https://github.com/apache/echarts/issues/14952

Also ee related `select.disabled` [PR](https://github.com/apache/echarts/pull/15534) by @susiwen8 .

### Fixed issues

https://github.com/apache/echarts/issues/14952

## Misc

- [x] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

Disable emphasis state of whole series

```ts
series: [{
  emphasis: {
     disabled: true
  }
}]
```

Disable emphasis state of single data

```ts
series: [{
  data: [{
      name: 'xxx',
      emphasis: { disabled: true }
  }]
}]
```

Disable emphasis state in custom series

```ts
renderItem() {
  return {
      type: 'group',
      emphasisDisabled: true
  }
}
```

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by plainheart — COMMENTED** [review]
It seems the first test case in `line-visual2.html` doesn't work anymore.

|  Before   | Current  |
|  :----:  | :----:  |
| image | image |

**Comment by pissang** [comment]
@plainheart Seems it's introduced by gradient color highlight and animation in https://github.com/apache/echarts/pull/16225  https://github.com/ecomfe/zrender/pull/857

**Comment by pissang** [comment]
@plainheart Turns out it's a very stupid typo. https://github.com/ecomfe/zrender/compare/fix-gradient-animation?expand=1

**Review by plainheart — APPROVED** [review]
LGTM

**Pull request merged**
