### PR TITLE
feat(sampler): add min-max sampler function

### PR DESCRIPTION
**Pull request by snukhulov**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?
Add min-max sampler function

### Before: What was the problem?

In some cases min-max sampling algorithm fits line data more naturally than the existing ones. For example, for a sine with a lot of data points min-max sampler is the best choice.

Example.
The original sine without sampling (200 000 data points).
Снимок экрана 2023-11-07 в 00 42 48

Using 'average' sampler
Снимок экрана 2023-11-07 в 00 44 15

Using 'lttb' sampler
Снимок экрана 2023-11-07 в 00 43 58

Using 'max' sampler
Снимок экрана 2023-11-07 в 00 43 39

Using 'min' sampler
Снимок экрана 2023-11-07 в 00 43 18

### After: How does it behave after the fixing?

Using new 'minmax' sampler
Снимок экрана 2023-11-07 в 01 08 29

## Document Info

One of the following should be checked.

- [ ] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [x] The document changes have been made in apache/echarts-doc#374

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Wily96 — APPROVED** [review]

**Review by Ovilia — COMMENTED** [review]
This seems to be a great idea. Can you explain what min-max mean first?

**Comment by snukhulov** [comment]
> This seems to be a great idea. Can you explain what min-max mean first?

Thank you.
Like 'min' sampler that highlights an extremum (turning-point) at a local minimum and like 'max' sampler that highlights an extremum at a local maximum, 'minmax' sampler highlights the larger extremum (minimum or maximum) at a local frame of data points.
'minmax' sampler is suitable for sine or other periodic data

**Comment by Ovilia** [comment]
Thanks for your explanation. Can you provide a link or something for further understanding? Is this a concept well-known or you invented it?

**Comment by snukhulov** [comment]
> Thanks for your explanation. Can you provide a link or something for further understanding? Is this a concept well-known or you invented it?

It's my own implementation of the [known min-max downsampling algorithm](https://www.chartjs.org/docs/latest/configuration/decimation.html).

**Review by hexiaokang — APPROVED** [review]

**Review by Ovilia — CHANGES_REQUESTED** [review]
Thanks! Please also add test cases in `test/line-sampling.html`. Please pay special attention both to the cases where there are negative values or not.

**Comment by snukhulov** [comment]
> Thanks! Please also add test cases in `test/line-sampling.html`. Please pay special attention both to the cases where there are negative values or not.

I added the described test cases

**Review by Ovilia — APPROVED** [review]
Thanks for your contribution! This will be released in the next version.

**Comment by Ovilia** [comment]
Updated demo [here](https://echarts.apache.org/examples/zh/editor.html?version=PR-19279%4077a3723&code=MYewdgzgLgBAZgJwKYEcCuSzAJ4wLwwDsADANwBQoksAtgIYDmYAllGgCZL4wBMZl4aPGYJoAZWZgkAETpQ63ANoBdClSEQkVdhKmz5S1QOrDRUXUgDycOJtgF-62Ju0XrtpPZgBWR4OfyCF5SAO4w-kgAFADkfDwAjAC0xADMySkAKvHeAFwpxDnExAB0RcQAWtEAlBRwIAgwkQA2njDM3GRtMAA8MPEAnABsncwA1KNVMADe5DAwTjDsclwEoeHLkdB0QcUMnhnMNFGTo201s_P-MFCHK10A9H1lFHMtsABudE0Y3JEAsnIABbFCCSSI8GAAKhgAKgwIACgBJKHwZDoTA4FE3I6TaH0JisDhIKrFKAgABizAAHkh2JEUuc5sw4I12r1Bil-jAAD7croAPhg_QALAzphc5nAROJJDI5HRigAHNAQQGRRRLKBIAA0ME-3y4pylZjcNjsykZcxgLnAOll-gVytV6s1OpgiUi-p-iWtWltpo8UCqFpeMAAvjAkE1NG0WZF2nhE0KUsLJjMraYZXp5UqVWqNctdWA0E0miGJb7XPac07866iyWy5aw-QW-QQIqbuBuOnrqwWjlptckFSoIPog7ouHtRcySAmjdFYOptcEMwGHsEOO6FTmBBorqd3v4SBJFqt0O6Cx6F2wIOoAgfhGwzPXkg9mB2MuK5q6IPFNEoJgJEVKAEQEgADwKBJTxKmB4wNEvjutaYJgZB0GwcoFwvhcv7lCAIA0P-FYrsgXzYkg96Pm6VIAIK7hAiKfiO_7ELq8TKLqUoLkgCB_CAnDjiESB0AA1pS3EIFO2EZiuUDYIqFHwZIoKcHBpELrclEYLqtH0YxnBUixbHKOGFwcbO-FNAARiAhlDnAwlsMgy7WnQ7xIDRDH4opUwvjAyDQPUPnPtOFy6XuLlyQp47kVJr4wNgdERTAijERWcxRYp0RekgB7pTAiogKCt7ji0cBQHlGZzGAdBHDFty6vu8UZjQkiDokvjNVa9B2fERRdXMAD6RzsMwaCEfBQEgRBUHFDBVTRBW0lWr2GaZeOOWVVVhXFcw4ClUg5VbRmNV1fB5GNcd3Vte6nX5T1g59ax-XDbSY0TQhxBIVNqGzfNi0Zi2czmXMmhrkgEBETJ-WnVlP0zehC0Ddc8lZU0spXaDWpLpNgQVcjqogCEYjYDQNlNIOcBfJoyOJXpTF2c9VWuTQiro2ADDjq1YA9ZjlxgFIwBQAAco2kPwNTOr5b-lPSuY1byEtXWrVasPjohPrw2hc2wcj63wezuUE9j45bEEfOE8TpPk5Tku00lDEM49BO1Wzkic_B3O88jVCCyLYu29GUvMzLlb-grdBLWZrakEAA)

**Comment by sulivanganter** [comment]
Hi, @snukhulov 

I think there might be something wrong. If you change the number of samples in your example to 100,000, [updated exemple](https://echarts.apache.org/examples/en/editor.html?version=5.5.0&code=MYewdgzgLgBAZgJwKYEcCuSzAJ4wLwwDsADANwBQoksAtgIYDmYAllGgCZL4wBMZl4aPGYJoAZWZgkAETpQ63ANoBdClSEQkVdhKmz5S1QOrDRUXUgDycOJtgF-62Ju0XrtpPZgBWR4OfyCF5SAO4w-kgAFADkfDwAjAC0xADMySkAKvHeAFwpxDnExAB0RcQAWtEAlBRwIAgwkQA2njDM3GRtMAA8MPFlRaRtANTDVTAA3uQwME4w7HJcBKHhi5HQdEHFDJ4ZzDRR48NtNdOz_jBQ-0tdAPR9ZRQzLbAAbnRNGNyRALJyABbFCCSSI8GAAKhgfyggIACgBJCHwZDoTA4JFXA7jSH0JisDhIKrFKAgABizAAHkh2JEUqcZsw4I12r0AGwpACcMAAPtyugA-GAcgAsdMmZxmcBE4kkMjkdGKAAc0BB_pFFAsoEgADQwd6fLjHKVmNw2OzKekzGAucA6WX6BXK1XqzU6mCJSL6r6Ja1aW2mjxQKoWp4wAC-MCQTU0bSZkXaeETQpSwvGUytphlenlSpVao1i11YDQTSaIYlvtc9pzTvzrqLJbLlrD5Bb5BAiqu4G46curBaOUmlyQFKgg-iDui4e1ZxJICaV0Vg4mlwQzAYOwQ47oFOYEGiup3e9hIEkWq3Q7oLHoXbAg6gCC-EbDM-eSB2YHYy4rmrog8U0TAmAkQUoARASAAPAoElPEqYHjA0S-O61ogmBkHQbByhnC-Zy_uUIAgDQ_4ViuyAfJiSD3o-boUgAgruEDwp-I7_sQurxMoupSguSAID8ICcOOIRIHQADW5LcQgU7YRmK5QNgioUfBkjApwcGkQu1yURguq0fRjGcBSLFsco4ZnBxs74U0ABGICGUOcDCWwyDLtadCvEgNEMbiikTC-MDINA9Q-c-05nLpe4uXJCnjuRUmvjA2B0RFMCKMRFYzFFinRF6SAHulMCKiAwK3uOLRwFAeUZjMYB0AcMXXLq-7xRmNCSIOiS-M1Vr0HZ_SsflAD6BzsMwaCEfBQEgRBUHFDBVTRBW0lWr2GaZeOOWVVVhXFcw4ClUg5WbRmNV1fB5GNUd3Vte6nX5T1g59V1MxDdSo3jQhxBIZNqEzXNC0Zi2MzmTMmhrkgEBETJ-UnVl33Teh81PZc8lZU0sqXSDWpLhNgQVUjqogCEYjYDQNlNIOcAfJoSOJXpTF2f1VWuTQipo2ADDjq1YA9Rj5xgFIwBQAAco2EPwFTOr5b-FPSuY1byItXUrVaMPjohPpw2hs2wUja3wWzuX41j44bEEvME0TJNkxTEs00lDH0w9-O1azkgc_BXM80jVAC8Los29GktM9Llb-vLdCLWZrakEAA&pv=PR-19279%4077a3723) ,you can see the problem with returning just the absolute max value. 

This is just a suggestion and has not been tested:

You need two values for each frame for min and max, something like this:

```javascript
 minmax: function (frame) {
    let turningPointMaxValue = -Infinity;
    let turningPointMinValue = Infinity;

    for (let i = 0; i < frame.length; i++) {
        const originalValue = frame[i];

        if (originalValue > turningPointMaxValue) {
            turningPointMaxValue = originalValue;
        }
        
        if (originalValue < turningPointMinValue) {
            turningPointMinValue = originalValue;
        }
    }

    // Return an array with the min and max values
    return [turningPointMinValue, turningPointMaxValue];
}
```

**Comment by snukhulov** [comment]
> Hi, @snukhulov
> 
> I think there might be something wrong. If you change the number of samples in your example to 100,000, [updated exemple](https://echarts.apache.org/examples/en/editor.html?version=5.5.0&code=MYewdgzgLgBAZgJwKYEcCuSzAJ4wLwwDsADANwBQoksAtgIYDmYAllGgCZL4wBMZl4aPGYJoAZWZgkAETpQ63ANoBdClSEQkVdhKmz5S1QOrDRUXUgDycOJtgF-62Ju0XrtpPZgBWR4OfyCF5SAO4w-kgAFADkfDwAjAC0xADMySkAKvHeAFwpxDnExAB0RcQAWtEAlBRwIAgwkQA2njDM3GRtMAA8MPFlRaRtANTDVTAA3uQwME4w7HJcBKHhi5HQdEHFDJ4ZzDRR48NtNdOz_jBQ-0tdAPR9ZRQzLbAAbnRNGNyRALJyABbFCCSSI8GAAKhgfyggIACgBJCHwZDoTA4JFXA7jSH0JisDhIKrFKAgABizAAHkh2JEUqcZsw4I12r0AGwpACcMAAPtyugA-GAcgAsdMmZxmcBE4kkMjkdGKAAc0BB_pFFAsoEgADQwd6fLjHKVmNw2OzKekzGAucA6WX6BXK1XqzU6mCJSL6r6Ja1aW2mjxQKoWp4wAC-MCQTU0bSZkXaeETQpSwvGUytphlenlSpVao1i11YDQTSaIYlvtc9pzTvzrqLJbLlrD5Bb5BAiqu4G46curBaOUmlyQFKgg-iDui4e1ZxJICaV0Vg4mlwQzAYOwQ47oFOYEGiup3e9hIEkWq3Q7oLHoXbAg6gCC-EbDM-eSB2YHYy4rmrog8U0TAmAkQUoARASAAPAoElPEqYHjA0S-O61ogmBkHQbByhnC-Zy_uUIAgDQ_4ViuyAfJiSD3o-boUgAgruEDwp-I7_sQurxMoupSguSAID8ICcOOIRIHQADW5LcQgU7YRmK5QNgioUfBkjApwcGkQu1yURguq0fRjGcBSLFsco4ZnBxs74U0ABGICGUOcDCWwyDLtadCvEgNEMbiikTC-MDINA9Q-c-05nLpe4uXJCnjuRUmvjA2B0RFMCKMRFYzFFinRF6SAHulMCKiAwK3uOLRwFAeUZjMYB0AcMXXLq-7xRmNCSIOiS-M1Vr0HZ_SsflAD6BzsMwaCEfBQEgRBUHFDBVTRBW0lWr2GaZeOOWVVVhXFcw4ClUg5WbRmNV1fB5GNUd3Vte6nX5T1g59V1MxDdSo3jQhxBIZNqEzXNC0Zi2MzmTMmhrkgEBETJ-UnVl33Teh81PZc8lZU0sqXSDWpLhNgQVUjqogCEYjYDQNlNIOcAfJoSOJXpTF2f1VWuTQipo2ADDjq1YA9Rj5xgFIwBQAAco2EPwFTOr5b-FPSuY1byItXUrVaMPjohPpw2hs2wUja3wWzuX41j44bEEvME0TJNkxTEs00lDH0w9-O1azkgc_BXM80jVAC8Los29GktM9Llb-vLdCLWZrakEAA&pv=PR-19279%4077a3723) ,you can see the problem with returning just the absolute max value.
> 
> This is just a suggestion and has not been tested:
> 
> You need two values for each frame for min and max, something like this:
> 
> ```js
>  minmax: function (frame) {
>     let turningPointMaxValue = -Infinity;
>     let turningPointMinValue = Infinity;
> 
>     for (let i = 0; i < frame.length; i++) {
>         const originalValue = frame[i];
> 
>         if (originalValue > turningPointMaxValue) {
>             turningPointMaxValue = originalValue;
>         }
>         
>         if (originalValue < turningPointMinValue) {
>             turningPointMinValue = originalValue;
>         }
>     }
> 
>     // Return an array with the min and max values
>     return [turningPointMinValue, turningPointMaxValue];
> }
> ```

Hi! Thank you for the research and the suggestion!

You're right about there are some problems with the proposed min-max sampler function. It's designed for a sine periodic data like `y(x)=A*sin(x*w + n)`, but there is some sampling problems with aperiodic component of a signal (like `y(x)=A*sin(x*w + n) + k`).

Your suggestion looks great, but I have some doubts about returning type of your function. I think it only could be `number`, but couldn't be array of numbers.

I thought about improvement of the proposed min-max sampler, but there is motivation to keep it simple like other existing sampling functions.

But I'am still looking for an improvement of min-max sampler function that could solve sampling problem of periodic functions with aperiodic components like `y(x)=A*sin(x*w + n) + k` and could be simple at the same time.

**Pull request merged**
