### PR TITLE
fix(12146): drag map into view once roamed away

### PR DESCRIPTION
**Pull request by KrzysztofMadejski**
## Brief Information

This pull request is in the type of:

- [ x ] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

Map can be dragged into the view once roamed away.  I branched off v4.9.0 tag so it could be fixed within 4.9.0 pipeline still. I haven't seen a branch for v4 development.

### Fixed issues

This solves #12146

### Before: What was the problem?

see https://github.com/apache/incubator-echarts/issues/12146
for explanation and video.

### After: How is it fixed in this PR?

Check if mousedown even falls into map rect box is removed. All events within canvas are handled.

### Are there any API changes?

- [ ] The API has been changed. -> NO

### Related test cases or examples to use the new APIs

I added `map-drag-out-and-in.html` visual test case. As it is my first PR I'm not sure if I done it right. 

I'm also not sure if I didn't break anything, but unit tests are passing.

### Merging options

- [ ] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by KrzysztofMadejski** [comment]
Question: should I also update dist folder? I was expecting that dist is built before publishing, not kept in the repo.

**Comment by susiwen8** [comment]
@KrzysztofMadejski thanks for contributing in Apache ECharts!

First, you should use TypeScript since we have migrate to TS since 5.0.

Second, Do not submit `dist` folder, only source code.

**Comment by KrzysztofMadejski** [comment]
Then I think you should not version dist folder in the repo. I believe it should only be built while publishing to npm.

Second: where should I use ts? I just removed one line, not added anything.

**Comment by pissang** [comment]
@KrzysztofMadejski Hi, we don't maintain multiple release branches, v4.x won't have new versions. The fix should always be based on the latest code in the master branch.

About the `dist` folder. It's common for developers to get the distribution file of the latest stable version on GitHub, some of who don't use npm. Also, CDN like cdnjs will fetch the distribution from this folder. It will only be built and committed before each stable release.

**Comment by KrzysztofMadejski** [comment]
Oh, that's very sad to hear you do not support old versions.

BTW: You can use Github Releases to serve "compiled" versions: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository

**Comment by KrzysztofMadejski** [comment]
closing as I'm not working anymore with echarts

**Pull request closed without merging**
