### PR TITLE
fix(line): distance bug in vertical or horizontal line #17162

### PR DESCRIPTION
**Pull request by horitaka**
Updated at Sep. 10.

## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### Fixed issues

- #17162: 
  - (a)Label distance X option does not work when a vertical line is set. 
  - (b)Label distance Y option does not work when a horizontal line is set.

### Before: What was the problem?
- Distance value is default ( [x, y] = [20, 8] ).
before_distance2008

- Distance value is [x, y] = [20, 5].
before_distance2005

- Distance value is [x, y] = [0, 0]. In this case, there is no problem before I fixed this issue.
before_distance00

### After: How does it behave after the fixing?
- Distance value is default ( [x, y] = [20, 8] ). I confirmed distance y value was working in horizontal line and other label positions didn't changed.
after_distance2008

- Distance value is [x, y] = [20, 5]. I confirmed distance x value was working in vertical line and other label positions didn't changed.
after_distance2005

- Distance value is [x, y] = [0, 0]. I confirmed any label positions didn't changed.
after_distance00

## Document Info

One of the following should be checked.

- [x] This PR doesn't relate to document changes
- [ ] The document should be updated later
- [ ] The document changes have been made in apache/echarts-doc#xxx

### ZRender Changes

- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — CHANGES_REQUESTED** [review]
Please check the test case in `test/markLine.html`. It seems there are some situations that haven't been considered. You may also update the test case if you think more cases should be tested.

**Comment by horitaka** [comment]
@Ovilia Thank you for your review. I checked and updated the test case in `test/markLine.html`. Also, I updated the screenshots in the pull request comment. Could you check again?

**Review by Ovilia — CHANGES_REQUESTED** [review]
Old:
image

New:
image

Diff:
image

I think at least the orange series is not correct. When distance is not defined, the `start` and `end` should always align to center.

As for the green series, I'm not very sure if it's a good design for start (bottom-left) to move to the left while end (top-left) to move to the right.

**Comment by Ovilia** [comment]
🔼 The result is generated by visual test. You can try it by yourself. `npm run test:visual`

**Comment by horitaka** [comment]
Thank you for your comment. I'm sorry, I misunderstood the expected behavior. I'll fix the code and commit again later.

**Comment by Ovilia** [comment]
@horitaka Never mind. Thank you for your contribution!

**Comment by horitaka** [comment]
After my investigation, I think the issue #17162 may not be a bug but correct behavior.

This issue is about the case `position = end`. I checked the current behavior for `position = insideEndTop, insideEndBottom`.

(1)For horizontal line, with position = insideEnd.
Vertical position isn't changed even if `distance.y` is set to [0, 30]

(2)For horizontal lines, `position = insideEndTop, insideEndBottom`.
Vertical position is changed if `distance.y` is set to [0, 30]
スクリーンショット 2022-10-29 11 02 50


Issue #17162 has the same behavior as (1). Therefore, I do not think this is a problem. If we want to move label position verticallly for a horizontal line, I think new options like `position = endTop, endBottom` are needed.


Of course, if this issue is determined to be a bug, I can fix this issue.

**Comment by Ovilia** [comment]
Thanks for your contribution anyway!

**Pull request closed without merging**
