### PR TITLE
Improve French translation

### PR DESCRIPTION
**Pull request by qortex**
Fix wording, typos, making it idiomatic & uniform

## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

Improve French translation.

### Before: What was the problem?

Awkward wording in French, and non-uniform.

### After: How is it fixed in this PR?

Rewording.

### Are there any API changes?

No

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

NA.

### Merging options

- [x] Please squash the commits into a single one when merge.

### CODE REVIEW

**Comment by susiwen8** [comment]
Merci pour votre contribution. Ca nous aide beaucoup!

**Review by susiwen8 — APPROVED** [review]

**Comment by plainheart** [comment]
Why was it merged into release branch but not master branch?

**Comment by susiwen8** [comment]
Oh no, I didn't see that.

**Comment by qortex** [comment]
Didn't find the best way to use this in my Angular project though. Kind of hacked a `registerLocale` call through ngx-echarts (but re-defined the locale variable). What is the idiomatic way? Thanks!

**Comment by susiwen8** [comment]
@wf123537200 could you answer this question?

**Pull request merged**
