### PR TITLE
feat(pie): support specifying coordinate system for pie series.

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [x] new feature
- [ ] others

### What does this PR do?

1. Add coordinate system support for pie series.
2. BMap extension supports `convertToPixel` & `convertFromPixel` API.

### Fixed issues

- #13851
- plainheart/echarts-extension-amap#38

### Before: What was the problem?

It's not convenient and not direct to display the pie series on Geo/BMap/AMap/Calendar coordinate system.

### After: How is it fixed in this PR?

Add a new option `coordinateSystem` for pie series.

## Misc

- [x] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

Please refer to `test/pie-coordinate-system.html`

### Merging options

- [ ] Please squash the commits into a single one when merging.

### CODE REVIEW

**Review by Ovilia — COMMENTED** [review]
LGTM. This looks very promising! 💐

**Comment by plainheart** [comment]
@Ovilia @pissang Is this feature planned in v5.3.3 or v5.4?

**Comment by pissang** [comment]
This feature deserved to be introduced as an important feature in the 5.4 article. But I also can't wait to have it in our next version. @plainheart I think I will leave this decision to you:)

**Comment by plainheart** [comment]
I had planned to release a new version of the amap extension for this feature in response to some developers' feedback. But it sounds better to introduce this feature in v5.4 so that the developer can know about it in time. I'm okay to leave it in v5.4. :D

**Review by pissang — APPROVED** [review]

**Pull request merged**
