### PR TITLE
design(#12933): tweak the z value of axisPointer component to make it be displayed under the symbol by default.

### LINKED ISSUE #12933: [Design] The line needs to be displayed under the symbol.
When hover, tooltip.axisPointer.line, the line needs to be displayed under the symbol.
The line should not destroy the integrity of the symbol.

7777png

### PR DESCRIPTION
**Pull request by plainheart**
## Brief Information

This pull request is in the type of:

- [ ] bug fixing
- [ ] new feature
- [x] others

### What does this PR do?

Design Changes. Closes #12933 

### Fixed issues

- #12933

### Before: What was the problem?

The `axisPointer` component displays above the symbol, which may destroy the integrity of the symbol.

### After: How is it fixed in this PR?

Set the `z` value of `axisPointer` component as a lower value `2` by default.

image

### Are there any API changes?

- [ ] The API has been changed.

### Related test cases or examples to use the new APIs

Any example with the option of `axisPointer`.

### CODE REVIEW

**Comment by pissang** [comment]
I'm thinking if the axisPointer line will be covered by the rectangle from `splitArea` if it's `z` is 0.

**Comment by plainheart** [comment]
> I'm thinking if the axisPointer line will be covered by the rectangle from `splitArea` if it's `z` is 0.

I've made a test in `test/axis-splitArea.html` and it seems that the axisPointer won't covered by splitArea.

image

**Comment by plainheart** [comment]
Found it may be covered by areaStyle.

**Comment by pissang** [comment]
LGTM, @100pah Can you think of other cases may be broken?

**Pull request closed without merging**
