### PR TITLE
fix(graph-circular.html/graph-grid-life.html/graph-label-rotate.html/…

### LINKED ISSUE #16178: [Bug] Max and Min zoom for graph charts
### Version

5.2.2

### Link to minimal reproduction

https://echarts.apache.org/examples/en/editor.html?c=graph-simple

### Steps To Reproduce

Currently happening

https://user-images.githubusercontent.com/6254009/144845990-8275252c-ab7c-4919-965d-d22d91229a14.mov

### Current Behavior

shouldn't zoom in/out too much

### Expected Behavior

Max zoom should not show a white page after lots of zooms in, and also zoom out shouldn't go so far.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by sahilsaini110**
…graph-multiple-edges.html/graph-simple.html/graph-symbol.html/graph.html/gridSimple.html): Max and Min zoom for graph charts. close #16178

## Brief Information

This pull request is in the type of:

- [x] bug fixing
- [ ] new feature
- [ ] others

### What does this PR do?

fix:Max and Min zoom for graphs charts.

### Fixed issues

 #16178

### Before: What was the problem?

Max and Min zoom for graphs charts was not good. It either zoom in too much or zoom out too much.

Screenshot (30)

Screenshot (31)

### After: How is it fixed in this PR?

Max and Min zoom for graphs charts is improved, now it has both upper and lower limit.

Screenshot (32)
Screenshot (33)

## Misc

- [ ] The API has been changed (apache/echarts-doc#xxx).
- [ ] This PR depends on ZRender changes (ecomfe/zrender#xxx).

### Related test cases or examples to use the new APIs

N.A.

### Merging options

- [x] Please squash the commits into a single one when merging.

### CODE REVIEW

**Comment by Ovilia** [comment]
Hi! Thanks for your contribution. Please do not include the changes under `dist`.

**Comment by sahilsaini110** [comment]
I am trying to figure out the way so either I have to force push it or I have to close the pr and raise another one.
Or do you have any better suggestions then plz let me know?

**Comment by sahilsaini110** [comment]
Is it allowed to force push?

**Comment by pissang** [comment]
@sahilsaini110 You can do anything on your branch. We will squash merge your PR

**Comment by sahilsaini110** [comment]
> Hi! Thanks for your contribution. Please do not include the changes under `dist`.

i have done this you may plzzz check now

**Comment by sahilsaini110** [comment]
@Ovilia @pissang may u now check this as I have done the changes

**Comment by sahilsaini110** [comment]
@pissang may u plz review this pr

**Comment by pissang** [comment]
What's this PR for. It only changes the test cases

**Comment by sahilsaini110** [comment]
> What's this PR for. It only changes the test cases

that was the issue I think that the zoom effect was working properly.

**Comment by sahilsaini110** [comment]
> > What's this PR for. It only changes the test cases
> 
> that was the issue I think that the zoom effect wasn't working properly.

ooo ok ok I have made the changes in test file not in src sorry sorry I will correct may you plz help me a little bit.

**Comment by pissang** [comment]
I'm going to close this PR. Feel free to open a new one for the source code fix.

**Pull request closed without merging**
